ET System: et_remote.c File Reference
et_remote.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <netdb.h>
#include <sys/time.h>
#include "et_private.h"
#include "et_network.h"
Functions
int etr_open (et_sys_id *id, const char *et_filename, et_openconfig openconfig)
int etr_close (et_sys_id id)
int etr_forcedclose (et_sys_id id)
int etr_kill (et_sys_id id)
int etr_alive (et_sys_id id)
int etr_wait_for_alive (et_sys_id id)
int etr_wakeup_attachment (et_sys_id id, et_att_id att)
int etr_wakeup_all (et_sys_id id, et_stat_id stat_id)
int etr_station_create_at (et_sys_id id, et_stat_id *stat_id, const char *stat_name, et_statconfig sconfig, int position, int parallelposition)
int etr_station_create (et_sys_id id, et_stat_id *stat_id, const char *stat_name, et_statconfig sconfig)
int etr_station_remove (et_sys_id id, et_stat_id stat_id)
int etr_station_attach (et_sys_id id, et_stat_id stat_id, et_att_id *att)
int etr_station_detach (et_sys_id id, et_att_id att)
int etr_station_setposition (et_sys_id id, et_stat_id stat_id, int position, int parallelposition)
int etr_station_getposition (et_sys_id id, et_stat_id stat_id, int *position, int *parallelposition)
int etr_station_isattached (et_sys_id id, et_stat_id stat_id, et_att_id att)
int etr_station_exists (et_sys_id id, et_stat_id *stat_id, const char *stat_name)
int etr_station_setselectwords (et_sys_id id, et_stat_id stat_id, int select[])
int etr_station_getselectwords (et_sys_id id, et_stat_id stat_id, int select[])
int etr_station_getlib (et_sys_id id, et_stat_id stat_id, char *lib)
int etr_station_getclass (et_sys_id id, et_stat_id stat_id, char *classs)
int etr_station_getfunction (et_sys_id id, et_stat_id stat_id, char *function)
int etr_station_getattachments (et_sys_id id, et_stat_id stat_id, int *numatts)
int etr_station_getstatus (et_sys_id id, et_stat_id stat_id, int *status)
int etr_station_getinputcount (et_sys_id id, et_stat_id stat_id, int *cnt)
int etr_station_getoutputcount (et_sys_id id, et_stat_id stat_id, int *cnt)
int etr_station_getblock (et_sys_id id, et_stat_id stat_id, int *block)
int etr_station_getuser (et_sys_id id, et_stat_id stat_id, int *user)
int etr_station_getrestore (et_sys_id id, et_stat_id stat_id, int *restore)
int etr_station_getselect (et_sys_id id, et_stat_id stat_id, int *select)
int etr_station_getcue (et_sys_id id, et_stat_id stat_id, int *cue)
int etr_station_getprescale (et_sys_id id, et_stat_id stat_id, int *prescale)
int etr_station_setblock (et_sys_id id, et_stat_id stat_id, int block)
int etr_station_setuser (et_sys_id id, et_stat_id stat_id, int user)
int etr_station_setrestore (et_sys_id id, et_stat_id stat_id, int restore)
int etr_station_setprescale (et_sys_id id, et_stat_id stat_id, int prescale)
int etr_station_setcue (et_sys_id id, et_stat_id stat_id, int cue)
int etr_system_gettemps (et_sys_id id, int *temps)
int etr_system_gettempsmax (et_sys_id id, int *tempsmax)
int etr_system_getstations (et_sys_id id, int *stations)
int etr_system_getstationsmax (et_sys_id id, int *stationsmax)
int etr_system_getprocs (et_sys_id id, int *procs)
int etr_system_getprocsmax (et_sys_id id, int *procsmax)
int etr_system_getattachments (et_sys_id id, int *atts)
int etr_system_getattsmax (et_sys_id id, int *attsmax)
int etr_system_getheartbeat (et_sys_id id, int *heartbeat)
int etr_system_getpid (et_sys_id id, int *pid)
int etr_system_getgroupcount (et_sys_id id, int *groupCnt)
int etr_attach_geteventsput (et_sys_id id, et_att_id att_id, uint64_t *events)
int etr_attach_geteventsget (et_sys_id id, et_att_id att_id, uint64_t *events)
int etr_attach_geteventsdump (et_sys_id id, et_att_id att_id, uint64_t *events)
int etr_attach_geteventsmake (et_sys_id id, et_att_id att_id, uint64_t *events)
int et_event_setdatabuffer (et_sys_id id, et_event *pe, void *data)
This routine set an event's data buffer for a remote user.
int etr_event_new (et_sys_id id, et_att_id att, et_event **ev, int mode, struct timespec *deltatime, size_t size)
int etr_events_new (et_sys_id id, et_att_id att, et_event *evs[], int mode, struct timespec *deltatime, size_t size, int num, int *nread)
int etr_events_new_group (et_sys_id id, et_att_id att, et_event *evs[], int mode, struct timespec *deltatime, size_t size, int num, int group, int *nread)
int etr_event_get (et_sys_id id, et_att_id att, et_event **ev, int mode, struct timespec *deltatime)
int etr_events_get (et_sys_id id, et_att_id att, et_event *evs[], int mode, struct timespec *deltatime, int num, int *nread)
int etr_event_put (et_sys_id id, et_att_id att, et_event *ev)
int etr_events_put (et_sys_id id, et_att_id att, et_event *evs[], int num)
int etr_event_dump (et_sys_id id, et_att_id att, et_event *ev)
int etr_events_dump (et_sys_id id, et_att_id att, et_event *evs[], int num)
Function Documentation
etr_alive()
int etr_alive (et_sys_id id)
References et_id_t::debug, ET_DEBUG_ERROR, et_logmsg(), ET_NET_ALIVE, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_alive().
etr_attach_geteventsdump()
int etr_attach_geteventsdump (et_sys_id id, et_att_id att_id, uint64_t * events)
Referenced by et_attach_geteventsdump().
etr_attach_geteventsget()
int etr_attach_geteventsget (et_sys_id id, et_att_id att_id, uint64_t * events)
Referenced by et_attach_geteventsget().
etr_attach_geteventsmake()
int etr_attach_geteventsmake (et_sys_id id, et_att_id att_id, uint64_t * events)
Referenced by et_attach_geteventsmake().
etr_attach_geteventsput()
int etr_attach_geteventsput (et_sys_id id, et_att_id att_id, uint64_t * events)
Referenced by et_attach_geteventsput().
etr_close()
int etr_close (et_sys_id id)
References et_id_t::debug, ET_DEBUG_ERROR, et_id_destroy(), et_logmsg(), ET_NET_CLOSE, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_close().
etr_event_dump()
int etr_event_dump (et_sys_id id, et_att_id att, et_event * ev)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_EV_DUMP, ET_OK, et_tcp_lock(), et_tcp_unlock(), et_event_t::modify, et_event_t::pdata, et_event_t::place, and et_id_t::sockfd.
Referenced by et_event_dump().
etr_event_get()
int etr_event_get (et_sys_id id, et_att_id att, et_event ** ev, int mode, struct timespec * deltatime)
References et_id_t::bit64, et_event_t::byteorder, et_event_t::control, et_event_t::datastatus, et_id_t::debug, ET_64BIT_UINT, ET_DATA_MASK, ET_DATA_SHIFT, ET_DEBUG_ERROR, ET_DUMP, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_TIMEOUT, ET_ERROR_WRITE, et_init_event(), et_logmsg(), ET_MODIFY, ET_MODIFY_HEADER, ET_NET_EV_GET, ET_OK, ET_PRIORITY_MASK, ET_SLEEP, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), ET_TIMED, ET_WAIT_MASK, et_event_t::length, et_event_t::memsize, et_event_t::modify, et_event_t::pdata, et_event_t::place, et_event_t::priority, and et_id_t::sockfd.
Referenced by et_event_get().
etr_event_new()
int etr_event_new (et_sys_id id, et_att_id att, et_event ** ev, int mode, struct timespec * deltatime, size_t size)
References et_id_t::bit64, et_id_t::debug, et_id_t::esize, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_TIMEOUT, ET_ERROR_WRITE, ET_EVENT_TEMP, ET_HIGHINT, et_init_event(), et_logmsg(), ET_LOWINT, ET_MODIFY, ET_NET_EV_NEW, ET_NOALLOC, ET_OK, ET_SLEEP, et_tcp_lock(), et_tcp_unlock(), ET_TIMED, ET_WAIT_MASK, et_event_t::length, et_event_t::memsize, et_event_t::modify, et_event_t::owner, et_event_t::pdata, et_event_t::place, et_id_t::sockfd, and et_event_t::temp.
Referenced by et_event_new().
etr_event_put()
int etr_event_put (et_sys_id id, et_att_id att, et_event * ev)
References et_event_t::byteorder, et_event_t::control, et_event_t::datastatus, et_id_t::debug, ET_DATA_SHIFT, ET_DEBUG_ERROR, ET_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_WRITE, ET_HIGHINT, et_logmsg(), ET_LOWINT, ET_MODIFY, ET_NET_EV_PUT, ET_NOALLOC, ET_OK, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), et_event_t::length, et_event_t::memsize, et_event_t::modify, et_event_t::owner, et_event_t::pdata, et_event_t::place, et_event_t::priority, and et_id_t::sockfd.
Referenced by et_event_put().
etr_events_dump()
int etr_events_dump (et_sys_id id, et_att_id att, et_event * evs[], int num)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_WRITE, et_logmsg(), ET_NET_EVS_DUMP, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_events_dump().
etr_events_get()
int etr_events_get (et_sys_id id, et_att_id att, et_event * evs[], int mode, struct timespec * deltatime, int num, int * nread)
References et_id_t::bit64, et_event_t::byteorder, et_event_t::control, et_event_t::datastatus, et_id_t::debug, ET_64BIT_UINT, ET_DATA_MASK, ET_DATA_SHIFT, ET_DEBUG_ERROR, ET_DUMP, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_TIMEOUT, ET_ERROR_WRITE, et_init_event(), et_logmsg(), ET_MODIFY, ET_MODIFY_HEADER, ET_NET_EVS_GET, ET_OK, ET_PRIORITY_MASK, ET_SLEEP, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), ET_TIMED, ET_WAIT_MASK, et_event_t::length, et_event_t::memsize, et_event_t::modify, et_event_t::place, et_event_t::priority, and et_id_t::sockfd.
Referenced by et_events_get().
etr_events_new()
int etr_events_new (et_sys_id id, et_att_id att, et_event * evs[], int mode, struct timespec * deltatime, size_t size, int num, int * nread)
References et_id_t::bit64, et_id_t::debug, et_id_t::esize, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_TIMEOUT, ET_ERROR_WRITE, ET_EVENT_NORMAL, ET_EVENT_TEMP, ET_HIGHINT, et_init_event(), et_logmsg(), ET_LOWINT, ET_MODIFY, ET_NET_EVS_NEW, ET_NOALLOC, ET_OK, ET_SLEEP, et_tcp_lock(), et_tcp_unlock(), ET_TIMED, ET_WAIT_MASK, et_event_t::length, et_event_t::memsize, et_event_t::modify, et_event_t::owner, et_event_t::place, et_id_t::sockfd, and et_event_t::temp.
Referenced by et_events_new().
etr_events_new_group()
int etr_events_new_group (et_sys_id id, et_att_id att, et_event * evs[], int mode, struct timespec * deltatime, size_t size, int num, int group, int * nread)
References et_id_t::bit64, et_id_t::debug, et_id_t::esize, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_TIMEOUT, ET_ERROR_WRITE, ET_EVENT_NORMAL, ET_EVENT_TEMP, ET_HIGHINT, et_init_event(), et_logmsg(), ET_LOWINT, ET_MODIFY, ET_NET_EVS_NEW_GRP, ET_NOALLOC, ET_OK, ET_SLEEP, et_tcp_lock(), et_tcp_unlock(), ET_TIMED, ET_WAIT_MASK, et_event_t::length, et_event_t::memsize, et_event_t::modify, et_event_t::owner, et_event_t::place, et_id_t::sockfd, and et_event_t::temp.
Referenced by et_events_new_group().
etr_events_put()
int etr_events_put (et_sys_id id, et_att_id att, et_event * evs[], int num)
References et_event_t::byteorder, et_id_t::debug, ET_DATA_SHIFT, ET_DEBUG_ERROR, ET_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_WRITE, ET_HIGHINT, et_logmsg(), ET_LOWINT, ET_MODIFY, ET_NET_EVS_PUT, ET_NOALLOC, ET_OK, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), et_event_t::length, et_event_t::pdata, and et_id_t::sockfd.
Referenced by et_events_put().
etr_forcedclose()
int etr_forcedclose (et_sys_id id)
References et_id_t::debug, ET_DEBUG_ERROR, et_id_destroy(), et_logmsg(), ET_NET_FCLOSE, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_forcedclose().
etr_kill()
int etr_kill (et_sys_id id)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_WRITE, et_id_destroy(), et_logmsg(), ET_NET_KILL, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_kill().
etr_open()
int etr_open (et_sys_id * id, const char * et_filename, et_openconfig openconfig)
References et_id_t::bit64, et_open_config_t::cast, et_open_config_t::debug_default, et_id_t::endian, et_id_t::esize, ET_64BIT_UINT, ET_DEBUG_ERROR, ET_DEBUG_INFO, ET_DIRECT, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_TIMEOUT, ET_ERROR_TOOMANY, ET_ERROR_WRITE, et_findserver(), et_freeAnswers(), ET_HOST_LOCAL, ET_IOV_MAX, et_logmsg(), ET_MAGIC_INT1, ET_MAGIC_INT2, ET_MAGIC_INT3, ET_MAXHOSTNAMELEN, ET_OK, ET_OPEN_NOWAIT, et_orderIpAddrs(), ET_REMOTE, et_id_t::ethost, et_open_config_t::host, et_open_config_t::interface, et_id_t::iov_max, et_id_t::lang, et_id_t::localAddr, et_id_t::locality, et_open_config_t::netinfo, et_id_t::nevents, et_id_t::nselects, et_id_t::port, et_open_config_t::serverport, et_id_t::sockfd, et_id_t::systemendian, et_open_config_t::tcpNoDelay, et_open_config_t::tcpRecvBufSize, et_open_config_t::tcpSendBufSize, et_open_config_t::timeout, et_id_t::version, and et_open_config_t::wait.
Referenced by et_open().
etr_station_attach()
int etr_station_attach (et_sys_id id, et_stat_id stat_id, et_att_id * att)
References et_id_t::debug, ET_DEBUG_ERROR, ET_DEBUG_WARN, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_WRITE, ET_IPADDRSTRLEN, et_logmsg(), ET_MAXHOSTNAMELEN, ET_NET_STAT_ATT, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_attach().
etr_station_create()
int etr_station_create (et_sys_id id, et_stat_id * stat_id, const char * stat_name, et_statconfig sconfig)
References ET_END, and etr_station_create_at().
etr_station_create_at()
int etr_station_create_at (et_sys_id id, et_stat_id * stat_id, const char * stat_name, et_statconfig sconfig, int position, int parallelposition)
References et_stat_config_t::block_mode, et_stat_config_t::classs, et_stat_config_t::cue, et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_EXISTS, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_CRAT, ET_OK, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), et_stat_config_t::flow_mode, et_stat_config_t::fname, et_stat_config_t::init, et_stat_config_t::lib, et_stat_config_t::prescale, et_stat_config_t::restore_mode, et_stat_config_t::select, et_stat_config_t::select_mode, et_id_t::sockfd, and et_stat_config_t::user_mode.
Referenced by et_station_create_at(), and etr_station_create().
etr_station_detach()
int etr_station_detach (et_sys_id id, et_att_id att)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_DET, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_detach().
etr_station_exists()
int etr_station_exists (et_sys_id id, et_stat_id * stat_id, const char * stat_name)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_EX, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_exists().
etr_station_getattachments()
int etr_station_getattachments (et_sys_id id, et_stat_id stat_id, int * numatts)
Referenced by et_station_getattachments().
etr_station_getblock()
int etr_station_getblock (et_sys_id id, et_stat_id stat_id, int * block)
Referenced by et_station_getblock().
etr_station_getclass()
int etr_station_getclass (et_sys_id id, et_stat_id stat_id, char * classs)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, ET_FILENAME_LENGTH, et_logmsg(), ET_NET_STAT_CLASS, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_getclass().
etr_station_getcue()
int etr_station_getcue (et_sys_id id, et_stat_id stat_id, int * cue)
Referenced by et_station_getcue().
etr_station_getfunction()
int etr_station_getfunction (et_sys_id id, et_stat_id stat_id, char * function)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, ET_FUNCNAME_LENGTH, et_logmsg(), ET_NET_STAT_FUNC, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_getfunction().
etr_station_getinputcount()
int etr_station_getinputcount (et_sys_id id, et_stat_id stat_id, int * cnt)
Referenced by et_station_getinputcount().
etr_station_getlib()
int etr_station_getlib (et_sys_id id, et_stat_id stat_id, char * lib)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, ET_FILENAME_LENGTH, et_logmsg(), ET_NET_STAT_LIB, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_getlib().
etr_station_getoutputcount()
int etr_station_getoutputcount (et_sys_id id, et_stat_id stat_id, int * cnt)
Referenced by et_station_getoutputcount().
etr_station_getposition()
int etr_station_getposition (et_sys_id id, et_stat_id stat_id, int * position, int * parallelposition)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_GPOS, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_getposition().
etr_station_getprescale()
int etr_station_getprescale (et_sys_id id, et_stat_id stat_id, int * prescale)
Referenced by et_station_getprescale().
etr_station_getrestore()
int etr_station_getrestore (et_sys_id id, et_stat_id stat_id, int * restore)
Referenced by et_station_getrestore().
etr_station_getselect()
int etr_station_getselect (et_sys_id id, et_stat_id stat_id, int * select)
Referenced by et_station_getselect().
etr_station_getselectwords()
int etr_station_getselectwords (et_sys_id id, et_stat_id stat_id, int select[])
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_GSW, ET_OK, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_getselectwords().
etr_station_getstatus()
int etr_station_getstatus (et_sys_id id, et_stat_id stat_id, int * status)
Referenced by et_station_getstatus().
etr_station_getuser()
int etr_station_getuser (et_sys_id id, et_stat_id stat_id, int * user)
Referenced by et_station_getuser().
etr_station_isattached()
int etr_station_isattached (et_sys_id id, et_stat_id stat_id, et_att_id att)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_ISAT, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_isattached().
etr_station_remove()
int etr_station_remove (et_sys_id id, et_stat_id stat_id)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_RM, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_remove().
etr_station_setblock()
int etr_station_setblock (et_sys_id id, et_stat_id stat_id, int block)
Referenced by et_station_setblock().
etr_station_setcue()
int etr_station_setcue (et_sys_id id, et_stat_id stat_id, int cue)
Referenced by et_station_setcue().
etr_station_setposition()
int etr_station_setposition (et_sys_id id, et_stat_id stat_id, int position, int parallelposition)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_SPOS, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_setposition().
etr_station_setprescale()
int etr_station_setprescale (et_sys_id id, et_stat_id stat_id, int prescale)
Referenced by et_station_setprescale().
etr_station_setrestore()
int etr_station_setrestore (et_sys_id id, et_stat_id stat_id, int restore)
Referenced by et_station_setrestore().
etr_station_setselectwords()
int etr_station_setselectwords (et_sys_id id, et_stat_id stat_id, int select[])
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_SSW, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_setselectwords().
etr_station_setuser()
int etr_station_setuser (et_sys_id id, et_stat_id stat_id, int user)
Referenced by et_station_setuser().
etr_system_getattachments()
int etr_system_getattachments (et_sys_id id, int * atts)
Referenced by et_system_getattachments().
etr_system_getattsmax()
int etr_system_getattsmax (et_sys_id id, int * attsmax)
Referenced by et_system_getattsmax().
etr_system_getgroupcount()
int etr_system_getgroupcount (et_sys_id id, int * groupCnt)
Referenced by et_system_setgroup().
etr_system_getheartbeat()
int etr_system_getheartbeat (et_sys_id id, int * heartbeat)
Referenced by et_system_getheartbeat().
etr_system_getpid()
int etr_system_getpid (et_sys_id id, int * pid)
Referenced by et_system_getpid().
etr_system_getprocs()
int etr_system_getprocs (et_sys_id id, int * procs)
Referenced by et_system_getprocs().
etr_system_getprocsmax()
int etr_system_getprocsmax (et_sys_id id, int * procsmax)
Referenced by et_system_getprocsmax().
etr_system_getstations()
int etr_system_getstations (et_sys_id id, int * stations)
Referenced by et_system_getstations().
etr_system_getstationsmax()
int etr_system_getstationsmax (et_sys_id id, int * stationsmax)
Referenced by et_system_getstationsmax().
etr_system_gettemps()
int etr_system_gettemps (et_sys_id id, int * temps)
Referenced by et_system_gettemps().
etr_system_gettempsmax()
int etr_system_gettempsmax (et_sys_id id, int * tempsmax)
Referenced by et_system_gettempsmax().
etr_wait_for_alive()
int etr_wait_for_alive (et_sys_id id)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_WAIT, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_wait_for_alive().
etr_wakeup_all()
int etr_wakeup_all (et_sys_id id, et_stat_id stat_id)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_WRITE, et_logmsg(), ET_NET_WAKE_ALL, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_wakeup_all().
etr_wakeup_attachment()
int etr_wakeup_attachment (et_sys_id id, et_att_id att)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_WRITE, et_logmsg(), ET_NET_WAKE_ATT, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_wakeup_attachment().