/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    // `com.github.spotbugs`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://coda.jlab.org/maven")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.loox.jloox)
    api(libs.com.loox.jlayout)
    api(libs.com.loox.jlm)
}

group = "org.jlab.coda"
version = "16.6.0"
description = "Event Transfer Java Library"
java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17
defaultTasks("build")

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.test {
//   useJUnitPlatform()
  failOnNoDiscoveredTests = false
}

// spotbugs {
//     toolVersion.set("4.7.3")
//     effort.set(com.github.spotbugs.snom.Effort.MAX)
//     reportLevel.set(com.github.spotbugs.snom.ReportLevel.LOW)
//     excludeFilter.set(file("config/spotbugs/exclude.xml"))
// }
