ET System: et_network.h File Reference
et_network.h File Reference
#include <arpa/inet.h>
#include <sys/ioctl.h>
#include "et_private.h"
Macros
#define SA struct sockaddr
#define ET_IOV_MAX 16 /* minimum for POSIX systems */
#define hton64(x) ntoh64(x)
#define ntoh64(x) x
#define ET_MAGIC_INT1 0x45543269
#define ET_MAGIC_INT2 0x73324772
#define ET_MAGIC_INT3 0x72656174
Functions
uint64_t et_ntoh64 (uint64_t n)
int et_CODAswap (int *src, int *dest, int nints, int same_endian)
int et_findserver2 (const char *etname, char *ethost, int *port, uint32_t *inetaddr, et_response **allETinfo, et_open_config *config, int trys, struct timeval *waittime, int debug)
void et_freeAnswers (et_response *answer)
codaIpList * et_orderIpAddrs (et_response *response, codaIpAddr *netinfo, char *preferredSubnet)
Macro Definition Documentation
ET_IOV_MAX
#define ET_IOV_MAX 16 /* minimum for POSIX systems */
ET_MAGIC_INT1
#define ET_MAGIC_INT1 0x45543269
ET_MAGIC_INT2
#define ET_MAGIC_INT2 0x73324772
ET_MAGIC_INT3
#define ET_MAGIC_INT3 0x72656174
hton64
#define hton64 (x) ntoh64(x)
ntoh64
#define ntoh64 (x) x
SA
#define SA struct sockaddr
Function Documentation
et_CODAswap()
int et_CODAswap (int * src, int * dest, int nints, int same_endian)
et_findserver2()
int et_findserver2 (const char * etname, char * ethost, int * port, uint32_t * inetaddr, et_response ** allETinfo, et_open_config * config, int trys, struct timeval * waittime, int debug)
Referenced by et_findlocality().
et_freeAnswers()
void et_freeAnswers (et_response * answer)
Referenced by etr_open().
et_ntoh64()
uint64_t et_ntoh64 (uint64_t n)
et_orderIpAddrs()
codaIpList* et_orderIpAddrs (et_response * response, codaIpAddr * netinfo, char * preferredSubnet)
Referenced by etr_open().