/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jlab_coda_et_EtJniAccess */

#ifndef _Included_org_jlab_coda_et_EtJniAccess
#define _Included_org_jlab_coda_et_EtJniAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    openLocalEtSystem
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_openLocalEtSystem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    closeLocalEtSystem
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_closeLocalEtSystem
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    killEtSystem
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_killEtSystem
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    putEvents
 * Signature: (JI[Lorg/jlab/coda/et/EtEventImpl;I)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_putEvents
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    dumpEvents
 * Signature: (JI[Lorg/jlab/coda/et/EtEventImpl;I)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_dumpEvents
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    getEvents
 * Signature: (JIIIII)[Lorg/jlab/coda/et/EtEventImpl;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jlab_coda_et_EtJniAccess_getEvents
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    newEvents
 * Signature: (JIIIIII)[Lorg/jlab/coda/et/EtEventImpl;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jlab_coda_et_EtJniAccess_newEvents__JIIIIII
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    newEvents
 * Signature: (JIIIIIII)[Lorg/jlab/coda/et/EtEventImpl;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jlab_coda_et_EtJniAccess_newEvents__JIIIIIII
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    createStation
 * Signature: (JLorg/jlab/coda/et/EtStationConfig;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_org_jlab_coda_et_EtJniAccess_createStation
  (JNIEnv *, jobject, jlong, jobject, jstring, jint, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    stationNameToObject
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_jlab_coda_et_EtJniAccess_stationNameToObject
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    attach
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jlab_coda_et_EtJniAccess_attach
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    detach
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_detach
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    removeStation
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_removeStation
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    setStationPosition
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_setStationPosition
  (JNIEnv *, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    wakeUpAttachment
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_EtJniAccess_wakeUpAttachment
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_jlab_coda_et_EtJniAccess
 * Method:    alive
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jlab_coda_et_EtJniAccess_alive
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
