/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jlab_coda_et_JniAccess */

#ifndef _Included_org_jlab_coda_et_JniAccess
#define _Included_org_jlab_coda_et_JniAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jlab_coda_et_JniAccess
 * Method:    openLocalEtSystem
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_JniAccess_openLocalEtSystem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_jlab_coda_et_JniAccess
 * Method:    putEvents
 * Signature: (JI[Lorg/jlab/coda/et/EventImpl;I)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_JniAccess_putEvents
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint);

/*
 * Class:     org_jlab_coda_et_JniAccess
 * Method:    dumpEvents
 * Signature: (JI[Lorg/jlab/coda/et/EventImpl;I)V
 */
JNIEXPORT void JNICALL Java_org_jlab_coda_et_JniAccess_dumpEvents
  (JNIEnv *, jobject, jlong, jint, jobjectArray, jint);

/*
 * Class:     org_jlab_coda_et_JniAccess
 * Method:    getEvents
 * Signature: (JIIIII)[Lorg/jlab/coda/et/EventImpl;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jlab_coda_et_JniAccess_getEvents
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_jlab_coda_et_JniAccess
 * Method:    newEvents
 * Signature: (JIIIIIII)[Lorg/jlab/coda/et/EventImpl;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jlab_coda_et_JniAccess_newEvents
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
