#
# If cMsg makefiles are called locally (not in a CODA build),
# override CODA variables with CMSG variables. Necessary if
# cMsg is made separately from CODA.
#
# Overwrite:
#     CODA_HOME      with CMSG_HOME
#     INSTALL_DIR    with CMSG_INSTALL
#     CODA_USE64BITS with CMSG_USE64BITS
#

ifdef CMSG_HOME
  CODA_HOME = $(CMSG_HOME)
endif

ifdef CMSG_INSTALL
  INSTALL_DIR = $(CMSG_INSTALL)
endif

ifdef CMSG_USE64BITS
  CODA_USE64BITS = $(CMSG_USE64BITS)
endif
