ET System: et_private.h File Reference
et_private.h File Reference
#include <stdint.h>
#include <stdlib.h>
#include <stdarg.h>
#include <stddef.h>
#include <limits.h>
#include <pthread.h>
#include "etCommonNetwork.h"
Data Structures
struct et_stat_config_t
Structure to hold parameters used to configure a station.
struct et_stat_data_t
Structure to hold the current state of a station.
struct et_list_t
Structure defining a station's input or output list of events.
struct et_fixin
Structure for fixing station input list.
struct et_fixout
Structure for fixing station output list.
struct et_fix
Struct to fix station's input and output linked lists after crash.
struct et_station_t
Structure defining a station.
struct et_proc
Structure containing local process info.
struct et_attach
Structure containing attachment info.
struct et_sys_config_t
Structure containing all info necessary to configure an ET system.
struct et_system_t
Structure containing all ET system information.
struct et_open_config_t
Structure holding all configuration parameters used to open an ET system.
struct et_id_t
Structure defining an ET system user id (one needed for each system in use) which contains pointers to key mem locations, config info, status info, node locality and remote node info.
struct et_mem_t
Structure containing info stored at front of shared or mapped memory.
struct et_response_t
Structure for holding an ET system's single response to ET client's broad/multicast.
struct et_netthread_t
Struct for passing data from system to network threads.
struct et_bridge_config_t
Structure to define configuration parameters used to bridge ET systems (transfer events between 2 systems).
Macros
#define ET_VERSION 16
Major version number.
#define ET_VERSION_MINOR 5
Minor version number.
#define ET_LANG_C 0
C language version of ET software.
#define ET_LANG_CPP 1
C++ language version of ET software.
#define ET_LANG_JAVA 2
Java language version of ET software.
#define ET_SYSTEM_TYPE_C 1
ET system implemented through C language library.
#define ET_SYSTEM_TYPE_JAVA 2
ET system implemented through Java language library.
#define ET_IPADDRSTRLEN 16
Max string length of dotted-decimal ip address.
#define ET_MAXHOSTNAMELEN 256
Max length of a host name including the terminating char.
#define ET_MAXADDRESSES 10
Max number of network addresses/names per host we'll examine.
#define ET_MON_SEC 20
Seconds between monitoring heartbeat for disconnecting from unresponsive clients.
#define ET_MON_NSEC 0
Nanoseconds between monitoring heartbeat for disconnecting from unresponsive clients.
#define ET_BEAT_SEC 0
Seconds between heartbeat (integer increment).
#define ET_BEAT_NSEC 500000000
Nanoseconds between heartbeat (integer increment).
#define ET_IS_ALIVE_SEC 2
Seconds between monitoring heartbeat for seeing if ET alive.
#define ET_IS_ALIVE_NSEC 0
Nanoseconds between monitoring heartbeat for seeing if ET alive.
#define ET_CLOSE_SEC 2
Seconds to wait before shutting down ET system.
#define ET_CLOSE_NSEC 500000000
Nanoseconds to wait before shutting down ET system.
#define ET_HBMODULO UINT_MAX
Max value for heartbeat.
#define ET_ATTACHMENTS_MAX 100
Maximum number of attachments allowed on the system.
#define ET_PROCESSES_MAX ET_ATTACHMENTS_MAX
Maximum number of local processes allowed to open the system.
#define ET_ATT_UNUSED 0
Attachment number not in use.
#define ET_ATT_ACTIVE 1
Attachment is active (attached to a station).
#define ET_ATT_CONTINUE 0
Attachment is normal.
#define ET_ATT_QUIT 1
Attachment must return immediately from ET API call.
#define ET_ATT_UNBLOCKED 0
Attachment is not blocked on a read.
#define ET_ATT_BLOCKED 1
Attachment is blocked on a read.
#define ET_ATT_NOSLEEP 0
Attachment is not in sleep mode.
#define ET_ATT_SLEEP 1
Attachment is in simulated sleep mode.
#define ET_PROC_CLOSED 0
Process has closed ET systems (no access to mapped memory).
#define ET_PROC_OPEN 1
Process has opened ET system (has access to mapped memory).
#define ET_PROC_ETDEAD 0
Process thinks ET system it is connected to is dead.
#define ET_PROC_ETOK 1
Process thinks ET system it is connected to is OK.
#define ET_STRUCT_NEW 0
Structure is newly created and not yet initialized.
#define ET_STRUCT_OK 1
Structure is initialized and ready for use.
#define ET_THREAD_KEEP 0
Keep thread around.
#define ET_THREAD_KILL 1
Kill thread.
#define ET_MUTEX_SHARE 0
Operating system can share pthread mutex between different local processes.
#define ET_MUTEX_NOSHARE 1
Operating system cannot share pthread mutex between different local processes.
#define ET_MUTEX_UNLOCKED 0
Pthread mutex is unlocked.
#define ET_MUTEX_LOCKED 1
Pthread mutex is locked.
#define ET_INITIAL_SHARED_MEM_DATA_BYTES 64
Size in bytes of the data stored at the beginning of the shared memory (these data give general info necessary for Java and C clients to handle the ET system file properly).
#define ET_FIX_READ 0
Fixing station's in/output event list after et_events_get or et_events_new.
#define ET_FIX_DUMP 1
Fixing station's in/output event list after et_events_dump.
#define ET_BIT64_MASK 0x1
Bit mask to select bit in bitInfo word of et_system structure identifying ET system's host running 64-bit OS.
#define ET_KILL_MASK 0x2
Bit mask to select bit in bitInfo word of et_system structure telling ET system to kill itself ASAP.
#define ET_GET_BIT64(x) ((x) & ET_BIT64_MASK)
Get the bit in the bitInfo word identifying ET system's host as running a 64-bit OS.
#define ET_GET_KILL(x) ((x) & ET_KILL_MASK)
Get the bit in the bitInfo word telling ET system to kill itself ASAP.
#define ET_SET_BIT64(x) ((x) | ET_BIT64_MASK)
Set the bit in the bitInfo word identifying ET system's host as running a 64-bit OS.
#define ET_SET_KILL(x) ((x) | ET_KILL_MASK)
Set the bit in the bitInfo word telling ET system to kill itself ASAP.
#define ET_NET_EV_GET_L 0
et_event_get
#define ET_NET_EVS_GET_L 1
et_events_get
#define ET_NET_EV_PUT_L 2
et_event_put
#define ET_NET_EVS_PUT_L 3
et_events_put
#define ET_NET_EV_NEW_L 4
et_event_new
#define ET_NET_EVS_NEW_L 5
et_events_new
#define ET_NET_EV_DUMP_L 6
et_event_dump
#define ET_NET_EVS_DUMP_L 7
et_events_dump
#define ET_NET_EVS_NEW_GRP_L 8
et_events_new_group
#define ET_NET_EV_GET 20
et_event_get
#define ET_NET_EVS_GET 21
et_events_get
#define ET_NET_EV_PUT 22
et_event_put
#define ET_NET_EVS_PUT 23
et_events_put
#define ET_NET_EV_NEW 24
et_event_new
#define ET_NET_EVS_NEW 25
et_events_new
#define ET_NET_EV_DUMP 26
et_event_dump
#define ET_NET_EVS_DUMP 27
et_events_dump
#define ET_NET_EVS_NEW_GRP 28
et_events_new_group
#define ET_NET_EVS_NEW_GRP_JAVA 29
#define ET_NET_ALIVE 40
et_alive
#define ET_NET_WAIT 41
et_wait_for_alive
#define ET_NET_CLOSE 42
et_close
#define ET_NET_FCLOSE 43
et_forcedclose
#define ET_NET_WAKE_ATT 44
et_wakeup_attachment
#define ET_NET_WAKE_ALL 45
et_wakeup_all
#define ET_NET_KILL 46
et_kill
#define ET_NET_STAT_ATT 60
et_station_attach
#define ET_NET_STAT_DET 61
et_station_detach
#define ET_NET_STAT_CRAT 62
et_station_create_at
#define ET_NET_STAT_RM 63
et_station_remove
#define ET_NET_STAT_SPOS 64
et_station_setposition
#define ET_NET_STAT_GPOS 65
et_station_getposition
#define ET_NET_STAT_ISAT 80
et_station_isattached
#define ET_NET_STAT_EX 81
et_station_exists
#define ET_NET_STAT_SSW 82
et_station_setselectwords
#define ET_NET_STAT_GSW 83
et_station_getselectwords
#define ET_NET_STAT_LIB 84
et_station_getlib
#define ET_NET_STAT_FUNC 85
et_station_getfunction
#define ET_NET_STAT_CLASS 86
et_station_getclass
#define ET_NET_STAT_GATTS 100
et_station_getattachments
#define ET_NET_STAT_STATUS 101
et_station_getstatus
#define ET_NET_STAT_INCNT 102
et_station_getinputcount
#define ET_NET_STAT_OUTCNT 103
et_station_getoutputcount
#define ET_NET_STAT_GBLOCK 104
et_station_getblock
#define ET_NET_STAT_GUSER 105
et_station_getuser
#define ET_NET_STAT_GRESTORE 106
et_station_getrestore
#define ET_NET_STAT_GPRE 107
et_station_getprescale
#define ET_NET_STAT_GCUE 108
et_station_getcue
#define ET_NET_STAT_GSELECT 109
et_station_getselect
#define ET_NET_STAT_SBLOCK 115
et_station_getblock
#define ET_NET_STAT_SUSER 116
et_station_getuser
#define ET_NET_STAT_SRESTORE 117
et_station_getrestore
#define ET_NET_STAT_SPRE 118
et_station_getprescale
#define ET_NET_STAT_SCUE 119
et_station_getcue
#define ET_NET_ATT_PUT 130
et_att_getput
#define ET_NET_ATT_GET 131
et_att_getget
#define ET_NET_ATT_DUMP 132
et_att_getdump
#define ET_NET_ATT_MAKE 133
et_att_getmake
#define ET_NET_SYS_TMP 150
et_system_gettemps
#define ET_NET_SYS_TMPMAX 151
et_system_gettempsmax
#define ET_NET_SYS_STAT 152
et_system_getstations
#define ET_NET_SYS_STATMAX 153
et_system_getstationsmax
#define ET_NET_SYS_PROC 154
et_system_getprocs
#define ET_NET_SYS_PROCMAX 155
et_system_getprocsmax
#define ET_NET_SYS_ATT 156
et_system_getattachments
#define ET_NET_SYS_ATTMAX 157
et_system_getattsmax
#define ET_NET_SYS_HBEAT 158
et_system_getheartbeat
#define ET_NET_SYS_PID 159
et_system_getpid
#define ET_NET_SYS_GRP 160
et_system_getgroup
#define ET_NET_SYS_DATA 170
send ET system data
#define ET_NET_SYS_HIST 171
send ET histogram data
#define ET_NET_SYS_GRPS 172
send size of each event group
#define ET_P2EVENT(etid, place) ((et_event *)((et_event *)(etid->events) + (place)))
Macro to get pointer to event from system id and event place.
#define ET_PEVENT2USR(p, offset) ((et_event *)((char *)(p) + (offset)))
Macro to change event pointer from ET system space to user space.
#define ET_PEVENT2ET(p, offset) ((et_event *)((char *)(p) - (offset)))
Macro to change event pointer from user space to ET system space.
#define ET_PSTAT2USR(p, offset) ((et_station *)((char *)(p) + (offset)))
Macro to change station pointer from ET system space to user space.
#define ET_PSTAT2ET(p, offset) ((et_station *)((char *)(p) - (offset)))
Macro to change station pointer from user space to ET system space.
#define ET_PDATA2USR(p, offset) ((void *)((char *)(p) + (offset)))
Macro to change data pointer from ET system space to user space.
#define ET_PDATA2ET(p, offset) ((void *)((char *)(p) - (offset)))
Macro to change data pointer from user space to ET system space.
#define ET_64BIT_UINT(hi, lo) (((uint64_t)(hi) << 32) | ((uint64_t)(lo) & 0x00000000FFFFFFFF))
Macro to take 2 ints (up to 64 bits each) and change into 1, unsigned 64-bit int (hi becomes the high 32 bits and lo becomes the low 32 bits).
#define ET_64BIT_INT(hi, lo) (((int64_t)(hi) << 32) | ((int64_t)(lo) & 0x00000000FFFFFFFF))
Macro to take 2 ints (up to 64 bits each) and change into 1, signed 64-bit int (hi becomes the high 32 bits and lo becomes the low 32 bits).
#define ET_64BIT_P(hi, lo) ((void *)(((uint64_t)(hi) << 32) | ((uint64_t)(lo) & 0x00000000FFFFFFFF)))
Macro to take 2 ints (up to 64 bits each) and change into 64-bit void pointer (hi becomes the high 32 bits and lo becomes the low 32 bits).
#define ET_HIGHINT(i) ((uint32_t)(((uint64_t)(i) >> 32) & 0x00000000FFFFFFFF))
Macro to take a 64-bit unsigned int and return the high 32 bits as an unsigned 32-bit int.
#define ET_LOWINT(i) ((uint32_t)((uint64_t)(i) & 0x00000000FFFFFFFF))
Macro to take a 64-bit unsigned int and return the low 32 bits as an unsigned 32-bit int.
Typedefs
typedef int(* ET_SELECT_FUNCPTR) (void *, et_stat_id, et_event *)
Defines event selection function.
typedef struct et_stat_config_t et_stat_config
Structure to hold parameters used to configure a station.
typedef struct et_stat_data_t et_stat_data
Structure to hold the current state of a station.
typedef struct et_list_t et_list
Structure defining a station's input or output list of events.
typedef struct et_station_t et_station
Structure defining a station.
typedef struct et_sys_config_t et_sys_config
Structure containing all info necessary to configure an ET system.
typedef struct et_system_t et_system
Structure containing all ET system information.
typedef struct et_open_config_t et_open_config
Structure holding all configuration parameters used to open an ET system.
typedef struct et_id_t et_id
Structure defining an ET system user id (one needed for each system in use) which contains pointers to key mem locations, config info, status info, node locality and remote node info.
typedef struct et_mem_t et_mem
Structure containing info stored at front of shared or mapped memory.
typedef struct et_response_t et_response
Structure for holding an ET system's single response to ET client's broad/multicast.
typedef struct et_netthread_t et_netthread
Struct for passing data from system to network threads.
typedef struct et_bridge_config_t et_bridge_config
Structure to define configuration parameters used to bridge ET systems (transfer events between 2 systems).
Functions
void et_station_lock (et_system *sys)
void et_station_unlock (et_system *sys)
void et_llist_lock (et_list *pl)
void et_llist_unlock (et_list *pl)
void et_system_lock (et_system *sys)
void et_system_unlock (et_system *sys)
void et_transfer_lock (et_station *ps)
void et_transfer_unlock (et_station *ps)
void et_transfer_lock_all (et_id *id)
void et_transfer_unlock_all (et_id *id)
void et_tcp_lock (et_id *id)
void et_tcp_unlock (et_id *id)
void et_memRead_lock (et_id *id)
void et_memWrite_lock (et_id *id)
void et_mem_unlock (et_id *id)
int et_mutex_locked (pthread_mutex_t *pmutex)
int et_repair_station (et_id *id, et_stat_id stat_id)
int et_repair_gc (et_id *id)
void et_init_station (et_station *ps)
void et_init_llist (et_list *pl)
void et_init_event (et_event *pe)
void et_init_event_ (et_event *pe)
void et_init_process (et_system *sys, et_proc_id id)
void et_init_attachment (et_system *sys, et_att_id id)
void et_init_histogram (et_id *id)
void et_init_stats_att (et_system *sys, et_att_id id)
void et_init_stats_allatts (et_system *sys)
void et_init_stats_station (et_station *ps)
void et_init_stats_allstations (et_id *id)
void et_init_stats_all (et_id *id)
int et_id_init (et_sys_id *id)
void et_id_destroy (et_sys_id id)
int et_station_write (et_id *id, et_stat_id stat_id, et_event *pe)
int et_station_nwrite (et_id *id, et_stat_id stat_id, et_event *pe[], int num)
int et_station_read (et_id *id, et_stat_id stat_id, et_event **pe, int _mode, et_att_id att, struct timespec *time)
int et_station_nread (et_id *id, et_stat_id stat_id, et_event *pe[], int mode, et_att_id att, struct timespec *time, int num, int *nread)
int et_station_nread_group (et_id *id, et_stat_id stat_id, et_event *pe[], int mode, et_att_id att, struct timespec *time, int num, int group, int *nread)
int et_station_dump (et_id *id, et_event *pe)
int et_station_ndump (et_id *id, et_event *pe[], int num)
int et_llist_read (et_list *pl, et_event **pe)
int et_llist_write (et_id *id, et_list *pl, et_event **pe, int num)
int et_llist_write_gc (et_id *id, et_event **pe, int num)
int et_restore_events (et_id *id, et_att_id att, et_stat_id stat_id)
void et_flush_events (et_id *id, et_att_id att, et_stat_id stat_id)
int et_mem_create (const char *name, size_t memsize, void **pmemory, size_t *totalSize)
void et_mem_write_first_block (char *ptr, uint32_t headerByteSize, uint64_t eventByteSize, uint64_t headerPosition, uint64_t dataPosition, uint64_t totalByteSize, uint64_t usedByteSize)
int et_mem_attach (const char *name, void **pmemory, et_mem *pInfo)
int et_mem_unmap (const char *name, void *pmem)
int et_mem_remove (const char *name, void *pmem)
int et_mem_size (const char *name, size_t *totalsize, size_t *usedsize)
void * et_temp_create (const char *name, size_t size)
void * et_temp_attach (const char *name, size_t size)
int et_temp_remove (const char *name, void *pmem, size_t size)
int etr_event_new (et_sys_id id, et_att_id att, et_event **ev, int mode, struct timespec *deltatime, size_t size)
int etr_events_new (et_sys_id id, et_att_id att, et_event *evs[], int mode, struct timespec *deltatime, size_t size, int num, int *nread)
int etr_events_new_group (et_sys_id id, et_att_id att, et_event *evs[], int mode, struct timespec *deltatime, size_t size, int num, int group, int *nread)
int etr_event_get (et_sys_id id, et_att_id att, et_event **ev, int wait, struct timespec *deltatime)
int etr_events_get (et_sys_id id, et_att_id att, et_event *evs[], int wait, struct timespec *deltatime, int num, int *nread)
int etr_event_put (et_sys_id id, et_att_id att, et_event *ev)
int etr_events_put (et_sys_id id, et_att_id att, et_event *evs[], int num)
int etr_event_dump (et_sys_id id, et_att_id att, et_event *ev)
int etr_events_dump (et_sys_id id, et_att_id att, et_event *evs[], int num)
int etr_open (et_sys_id *id, const char *et_filename, et_openconfig openconfig)
int etr_close (et_sys_id id)
int etr_forcedclose (et_sys_id id)
int etr_kill (et_sys_id id)
int etr_alive (et_sys_id id)
int etr_wait_for_alive (et_sys_id id)
int etr_wakeup_attachment (et_sys_id id, et_att_id att)
int etr_wakeup_all (et_sys_id id, et_stat_id stat_id)
int etr_station_create_at (et_sys_id id, et_stat_id *stat_id, const char *stat_name, et_statconfig sconfig, int position, int parallelposition)
int etr_station_create (et_sys_id id, et_stat_id *stat_id, const char *stat_name, et_statconfig sconfig)
int etr_station_remove (et_sys_id id, et_stat_id stat_id)
int etr_station_attach (et_sys_id id, et_stat_id stat_id, et_att_id *att)
int etr_station_detach (et_sys_id id, et_att_id att)
int etr_station_setposition (et_sys_id id, et_stat_id stat_id, int position, int parallelposition)
int etr_station_getposition (et_sys_id id, et_stat_id stat_id, int *position, int *parallelposition)
int etr_station_isattached (et_sys_id id, et_stat_id stat_id, et_att_id att)
int etr_station_exists (et_sys_id id, et_stat_id *stat_id, const char *stat_name)
int etr_station_getattachments (et_sys_id id, et_stat_id stat_id, int *numatts)
int etr_station_getstatus (et_sys_id id, et_stat_id stat_id, int *status)
int etr_station_getinputcount (et_sys_id id, et_stat_id stat_id, int *cnt)
int etr_station_getoutputcount (et_sys_id id, et_stat_id stat_id, int *cnt)
int etr_station_getselect (et_sys_id id, et_stat_id stat_id, int *select)
int etr_station_getlib (et_sys_id id, et_stat_id stat_id, char *lib)
int etr_station_getclass (et_sys_id id, et_stat_id stat_id, char *classs)
int etr_station_getfunction (et_sys_id id, et_stat_id stat_id, char *function)
int etr_station_getblock (et_sys_id id, et_stat_id stat_id, int *block)
int etr_station_setblock (et_sys_id id, et_stat_id stat_id, int block)
int etr_station_getuser (et_sys_id id, et_stat_id stat_id, int *user)
int etr_station_setuser (et_sys_id id, et_stat_id stat_id, int user)
int etr_station_getrestore (et_sys_id id, et_stat_id stat_id, int *restore)
int etr_station_setrestore (et_sys_id id, et_stat_id stat_id, int restore)
int etr_station_getprescale (et_sys_id id, et_stat_id stat_id, int *prescale)
int etr_station_setprescale (et_sys_id id, et_stat_id stat_id, int prescale)
int etr_station_getcue (et_sys_id id, et_stat_id stat_id, int *cue)
int etr_station_setcue (et_sys_id id, et_stat_id stat_id, int cue)
int etr_station_getselectwords (et_sys_id id, et_stat_id stat_id, int select[])
int etr_station_setselectwords (et_sys_id id, et_stat_id stat_id, int select[])
int etr_system_gettemps (et_sys_id id, int *temps)
int etr_system_gettempsmax (et_sys_id id, int *tempsmax)
int etr_system_getstations (et_sys_id id, int *stations)
int etr_system_getstationsmax (et_sys_id id, int *stationsmax)
int etr_system_getprocs (et_sys_id id, int *procs)
int etr_system_getprocsmax (et_sys_id id, int *procsmax)
int etr_system_getattachments (et_sys_id id, int *atts)
int etr_system_getattsmax (et_sys_id id, int *attsmax)
int etr_system_getheartbeat (et_sys_id id, int *heartbeat)
int etr_system_getpid (et_sys_id id, int *pid)
int etr_system_getgroupcount (et_sys_id id, int *groupCnt)
int etr_attach_geteventsput (et_sys_id id, et_att_id att_id, uint64_t *events)
int etr_attach_geteventsget (et_sys_id id, et_att_id att_id, uint64_t *events)
int etr_attach_geteventsdump (et_sys_id id, et_att_id att_id, uint64_t *events)
int etr_attach_geteventsmake (et_sys_id id, et_att_id att_id, uint64_t *events)
int etn_open (et_sys_id *id, const char *filename, et_openconfig openconfig)
int etn_close (et_sys_id id)
int etn_forcedclose (et_sys_id id)
int etn_kill (et_sys_id id)
int etn_alive (et_sys_id id)
int etn_wait_for_alive (et_sys_id id)
int etn_event_new (et_sys_id id, et_att_id att, et_event **ev, int mode, struct timespec *deltatime, size_t size)
int etn_events_new (et_sys_id id, et_att_id att, et_event *evs[], int mode, struct timespec *deltatime, size_t size, int num, int *nread)
int etn_events_new_group (et_sys_id id, et_att_id att, et_event *evs[], int mode, struct timespec *deltatime, size_t size, int num, int group, int *nread)
int etn_event_get (et_sys_id id, et_att_id att, et_event **ev, int mode, struct timespec *deltatime)
int etn_events_get (et_sys_id id, et_att_id att, et_event *evs[], int mode, struct timespec *deltatime, int num, int *nread)
int etn_event_put (et_sys_id id, et_att_id att, et_event *ev)
int etn_events_put (et_sys_id id, et_att_id att, et_event *evs[], int num)
int etn_event_dump (et_sys_id id, et_att_id att, et_event *ev)
int etn_events_dump (et_sys_id id, et_att_id att, et_event *evs[], int num)
int etl_open (et_sys_id *id, const char *filename, et_openconfig openconfig)
int etl_close (et_sys_id id)
int etl_forcedclose (et_sys_id id)
int etl_kill (et_sys_id id)
int etl_alive (et_sys_id id)
int etl_wait_for_alive (et_sys_id id)
int et_wait_for_system (et_sys_id id, struct timespec *timeout, const char *etname)
int et_look (et_sys_id *id, const char *filename)
int et_unlook (et_sys_id id)
void * et_cast_thread (void *arg)
void * et_netserver (void *arg)
int et_findserver (const char *etname, char *ethost, int *port, uint32_t *inetaddr, et_open_config *config, et_response **allETinfo, int debug)
int et_responds (const char *etname)
int et_sharedmutex (void)
int et_findlocality (const char *filename, et_openconfig openconfig)
This routine determines whether we are looking for the ET system locally, locally on some non-pthread-mutex-sharing operating system, or remotely.
int et_station_config_check (et_id *id, et_stat_config *sc)
This routine checks a station's configuration settings for internal inconsistencies or bad values.
int et_station_compare_parallel (et_id *id, et_stat_config *group, et_stat_config *config)
This routine compares all relevant station configuration parameters to see if both configs are compatible enough to belong in the same parallel station group.
void et_logmsg (char *sev, char *fmt,...)
Macro Definition Documentation
ET_64BIT_INT
#define ET_64BIT_INT (hi, lo) (((int64_t)(hi) << 32) | ((int64_t)(lo) & 0x00000000FFFFFFFF))
Macro to take 2 ints (up to 64 bits each) and change into 1, signed 64-bit int (hi becomes the high 32 bits and lo becomes the low 32 bits).
ET_64BIT_P
#define ET_64BIT_P (hi, lo) ((void *)(((uint64_t)(hi) << 32) | ((uint64_t)(lo) & 0x00000000FFFFFFFF)))
Macro to take 2 ints (up to 64 bits each) and change into 64-bit void pointer (hi becomes the high 32 bits and lo becomes the low 32 bits).
ET_64BIT_UINT
#define ET_64BIT_UINT (hi, lo) (((uint64_t)(hi) << 32) | ((uint64_t)(lo) & 0x00000000FFFFFFFF))
Macro to take 2 ints (up to 64 bits each) and change into 1, unsigned 64-bit int (hi becomes the high 32 bits and lo becomes the low 32 bits).
ET_ATT_ACTIVE
#define ET_ATT_ACTIVE 1
Attachment is active (attached to a station).
ET_ATT_BLOCKED
#define ET_ATT_BLOCKED 1
Attachment is blocked on a read.
ET_ATT_CONTINUE
#define ET_ATT_CONTINUE 0
Attachment is normal.
ET_ATT_NOSLEEP
#define ET_ATT_NOSLEEP 0
Attachment is not in sleep mode.
ET_ATT_QUIT
#define ET_ATT_QUIT 1
Attachment must return immediately from ET API call.
ET_ATT_SLEEP
#define ET_ATT_SLEEP 1
Attachment is in simulated sleep mode.
ET_ATT_UNBLOCKED
#define ET_ATT_UNBLOCKED 0
Attachment is not blocked on a read.
ET_ATT_UNUSED
#define ET_ATT_UNUSED 0
Attachment number not in use.
ET_ATTACHMENTS_MAX
#define ET_ATTACHMENTS_MAX 100
Maximum number of attachments allowed on the system.
ET_BEAT_NSEC
#define ET_BEAT_NSEC 500000000
Nanoseconds between heartbeat (integer increment).
ET_BEAT_SEC
#define ET_BEAT_SEC 0
Seconds between heartbeat (integer increment).
ET_BIT64_MASK
#define ET_BIT64_MASK 0x1
Bit mask to select bit in bitInfo word of et_system structure identifying ET system's host running 64-bit OS.
ET_CLOSE_NSEC
#define ET_CLOSE_NSEC 500000000
Nanoseconds to wait before shutting down ET system.
ET_CLOSE_SEC
#define ET_CLOSE_SEC 2
Seconds to wait before shutting down ET system.
ET_FIX_DUMP
#define ET_FIX_DUMP 1
Fixing station's in/output event list after et_events_dump.
ET_FIX_READ
#define ET_FIX_READ 0
Fixing station's in/output event list after et_events_get or et_events_new.
ET_GET_BIT64
#define ET_GET_BIT64 (x) ((x) & ET_BIT64_MASK)
Get the bit in the bitInfo word identifying ET system's host as running a 64-bit OS.
ET_GET_KILL
#define ET_GET_KILL (x) ((x) & ET_KILL_MASK)
Get the bit in the bitInfo word telling ET system to kill itself ASAP.
ET_HBMODULO
#define ET_HBMODULO UINT_MAX
Max value for heartbeat.
ET_HIGHINT
#define ET_HIGHINT (i) ((uint32_t)(((uint64_t)(i) >> 32) & 0x00000000FFFFFFFF))
Macro to take a 64-bit unsigned int and return the high 32 bits as an unsigned 32-bit int.
ET_INITIAL_SHARED_MEM_DATA_BYTES
#define ET_INITIAL_SHARED_MEM_DATA_BYTES 64
Size in bytes of the data stored at the beginning of the shared memory (these data give general info necessary for Java and C clients to handle the ET system file properly).
ET_IPADDRSTRLEN
#define ET_IPADDRSTRLEN 16
Max string length of dotted-decimal ip address.
ET_IS_ALIVE_NSEC
#define ET_IS_ALIVE_NSEC 0
Nanoseconds between monitoring heartbeat for seeing if ET alive.
ET_IS_ALIVE_SEC
#define ET_IS_ALIVE_SEC 2
Seconds between monitoring heartbeat for seeing if ET alive.
ET_KILL_MASK
#define ET_KILL_MASK 0x2
Bit mask to select bit in bitInfo word of et_system structure telling ET system to kill itself ASAP.
ET_LANG_C
#define ET_LANG_C 0
C language version of ET software.
ET_LANG_CPP
#define ET_LANG_CPP 1
C++ language version of ET software.
ET_LANG_JAVA
#define ET_LANG_JAVA 2
Java language version of ET software.
ET_LOWINT
#define ET_LOWINT (i) ((uint32_t)((uint64_t)(i) & 0x00000000FFFFFFFF))
Macro to take a 64-bit unsigned int and return the low 32 bits as an unsigned 32-bit int.
ET_MAXADDRESSES
#define ET_MAXADDRESSES 10
Max number of network addresses/names per host we'll examine.
ET_MAXHOSTNAMELEN
#define ET_MAXHOSTNAMELEN 256
Max length of a host name including the terminating char.
ET_MON_NSEC
#define ET_MON_NSEC 0
Nanoseconds between monitoring heartbeat for disconnecting from unresponsive clients.
ET_MON_SEC
#define ET_MON_SEC 20
Seconds between monitoring heartbeat for disconnecting from unresponsive clients.
ET_MUTEX_LOCKED
#define ET_MUTEX_LOCKED 1
Pthread mutex is locked.
ET_MUTEX_NOSHARE
#define ET_MUTEX_NOSHARE 1
Operating system cannot share pthread mutex between different local processes.
ET_MUTEX_SHARE
#define ET_MUTEX_SHARE 0
Operating system can share pthread mutex between different local processes.
ET_MUTEX_UNLOCKED
#define ET_MUTEX_UNLOCKED 0
Pthread mutex is unlocked.
ET_NET_ALIVE
#define ET_NET_ALIVE 40
et_alive
ET_NET_ATT_DUMP
#define ET_NET_ATT_DUMP 132
et_att_getdump
ET_NET_ATT_GET
#define ET_NET_ATT_GET 131
et_att_getget
ET_NET_ATT_MAKE
#define ET_NET_ATT_MAKE 133
et_att_getmake
ET_NET_ATT_PUT
#define ET_NET_ATT_PUT 130
et_att_getput
ET_NET_CLOSE
#define ET_NET_CLOSE 42
et_close
ET_NET_EV_DUMP
#define ET_NET_EV_DUMP 26
et_event_dump
ET_NET_EV_DUMP_L
#define ET_NET_EV_DUMP_L 6
et_event_dump
ET_NET_EV_GET
#define ET_NET_EV_GET 20
et_event_get
ET_NET_EV_GET_L
#define ET_NET_EV_GET_L 0
et_event_get
ET_NET_EV_NEW
#define ET_NET_EV_NEW 24
et_event_new
ET_NET_EV_NEW_L
#define ET_NET_EV_NEW_L 4
et_event_new
ET_NET_EV_PUT
#define ET_NET_EV_PUT 22
et_event_put
ET_NET_EV_PUT_L
#define ET_NET_EV_PUT_L 2
et_event_put
ET_NET_EVS_DUMP
#define ET_NET_EVS_DUMP 27
et_events_dump
ET_NET_EVS_DUMP_L
#define ET_NET_EVS_DUMP_L 7
et_events_dump
ET_NET_EVS_GET
#define ET_NET_EVS_GET 21
et_events_get
ET_NET_EVS_GET_L
#define ET_NET_EVS_GET_L 1
et_events_get
ET_NET_EVS_NEW
#define ET_NET_EVS_NEW 25
et_events_new
ET_NET_EVS_NEW_GRP
#define ET_NET_EVS_NEW_GRP 28
et_events_new_group
ET_NET_EVS_NEW_GRP_JAVA
#define ET_NET_EVS_NEW_GRP_JAVA 29
ET_NET_EVS_NEW_GRP_L
#define ET_NET_EVS_NEW_GRP_L 8
et_events_new_group
ET_NET_EVS_NEW_L
#define ET_NET_EVS_NEW_L 5
et_events_new
ET_NET_EVS_PUT
#define ET_NET_EVS_PUT 23
et_events_put
ET_NET_EVS_PUT_L
#define ET_NET_EVS_PUT_L 3
et_events_put
ET_NET_FCLOSE
#define ET_NET_FCLOSE 43
et_forcedclose
ET_NET_KILL
#define ET_NET_KILL 46
et_kill
ET_NET_STAT_ATT
#define ET_NET_STAT_ATT 60
et_station_attach
ET_NET_STAT_CLASS
#define ET_NET_STAT_CLASS 86
et_station_getclass
ET_NET_STAT_CRAT
#define ET_NET_STAT_CRAT 62
et_station_create_at
ET_NET_STAT_DET
#define ET_NET_STAT_DET 61
et_station_detach
ET_NET_STAT_EX
#define ET_NET_STAT_EX 81
et_station_exists
ET_NET_STAT_FUNC
#define ET_NET_STAT_FUNC 85
et_station_getfunction
ET_NET_STAT_GATTS
#define ET_NET_STAT_GATTS 100
et_station_getattachments
ET_NET_STAT_GBLOCK
#define ET_NET_STAT_GBLOCK 104
et_station_getblock
ET_NET_STAT_GCUE
#define ET_NET_STAT_GCUE 108
et_station_getcue
ET_NET_STAT_GPOS
#define ET_NET_STAT_GPOS 65
et_station_getposition
ET_NET_STAT_GPRE
#define ET_NET_STAT_GPRE 107
et_station_getprescale
ET_NET_STAT_GRESTORE
#define ET_NET_STAT_GRESTORE 106
et_station_getrestore
ET_NET_STAT_GSELECT
#define ET_NET_STAT_GSELECT 109
et_station_getselect
ET_NET_STAT_GSW
#define ET_NET_STAT_GSW 83
et_station_getselectwords
ET_NET_STAT_GUSER
#define ET_NET_STAT_GUSER 105
et_station_getuser
ET_NET_STAT_INCNT
#define ET_NET_STAT_INCNT 102
et_station_getinputcount
ET_NET_STAT_ISAT
#define ET_NET_STAT_ISAT 80
et_station_isattached
ET_NET_STAT_LIB
#define ET_NET_STAT_LIB 84
et_station_getlib
ET_NET_STAT_OUTCNT
#define ET_NET_STAT_OUTCNT 103
et_station_getoutputcount
ET_NET_STAT_RM
#define ET_NET_STAT_RM 63
et_station_remove
ET_NET_STAT_SBLOCK
#define ET_NET_STAT_SBLOCK 115
et_station_getblock
ET_NET_STAT_SCUE
#define ET_NET_STAT_SCUE 119
et_station_getcue
ET_NET_STAT_SPOS
#define ET_NET_STAT_SPOS 64
et_station_setposition
ET_NET_STAT_SPRE
#define ET_NET_STAT_SPRE 118
et_station_getprescale
ET_NET_STAT_SRESTORE
#define ET_NET_STAT_SRESTORE 117
et_station_getrestore
ET_NET_STAT_SSW
#define ET_NET_STAT_SSW 82
et_station_setselectwords
ET_NET_STAT_STATUS
#define ET_NET_STAT_STATUS 101
et_station_getstatus
ET_NET_STAT_SUSER
#define ET_NET_STAT_SUSER 116
et_station_getuser
ET_NET_SYS_ATT
#define ET_NET_SYS_ATT 156
et_system_getattachments
ET_NET_SYS_ATTMAX
#define ET_NET_SYS_ATTMAX 157
et_system_getattsmax
ET_NET_SYS_DATA
#define ET_NET_SYS_DATA 170
send ET system data
ET_NET_SYS_GRP
#define ET_NET_SYS_GRP 160
et_system_getgroup
ET_NET_SYS_GRPS
#define ET_NET_SYS_GRPS 172
send size of each event group
ET_NET_SYS_HBEAT
#define ET_NET_SYS_HBEAT 158
et_system_getheartbeat
ET_NET_SYS_HIST
#define ET_NET_SYS_HIST 171
send ET histogram data
ET_NET_SYS_PID
#define ET_NET_SYS_PID 159
et_system_getpid
ET_NET_SYS_PROC
#define ET_NET_SYS_PROC 154
et_system_getprocs
ET_NET_SYS_PROCMAX
#define ET_NET_SYS_PROCMAX 155
et_system_getprocsmax
ET_NET_SYS_STAT
#define ET_NET_SYS_STAT 152
et_system_getstations
ET_NET_SYS_STATMAX
#define ET_NET_SYS_STATMAX 153
et_system_getstationsmax
ET_NET_SYS_TMP
#define ET_NET_SYS_TMP 150
et_system_gettemps
ET_NET_SYS_TMPMAX
#define ET_NET_SYS_TMPMAX 151
et_system_gettempsmax
ET_NET_WAIT
#define ET_NET_WAIT 41
et_wait_for_alive
ET_NET_WAKE_ALL
#define ET_NET_WAKE_ALL 45
et_wakeup_all
ET_NET_WAKE_ATT
#define ET_NET_WAKE_ATT 44
et_wakeup_attachment
ET_P2EVENT
#define ET_P2EVENT (etid, place) ((et_event *)((et_event *)(etid->events) + (place)))
Macro to get pointer to event from system id and event place.
ET_PDATA2ET
#define ET_PDATA2ET (p, offset) ((void *)((char *)(p) - (offset)))
Macro to change data pointer from user space to ET system space.
ET_PDATA2USR
#define ET_PDATA2USR (p, offset) ((void *)((char *)(p) + (offset)))
Macro to change data pointer from ET system space to user space.
ET_PEVENT2ET
#define ET_PEVENT2ET (p, offset) ((et_event *)((char *)(p) - (offset)))
Macro to change event pointer from user space to ET system space.
ET_PEVENT2USR
#define ET_PEVENT2USR (p, offset) ((et_event *)((char *)(p) + (offset)))
Macro to change event pointer from ET system space to user space.
ET_PROC_CLOSED
#define ET_PROC_CLOSED 0
Process has closed ET systems (no access to mapped memory).
ET_PROC_ETDEAD
#define ET_PROC_ETDEAD 0
Process thinks ET system it is connected to is dead.
ET_PROC_ETOK
#define ET_PROC_ETOK 1
Process thinks ET system it is connected to is OK.
ET_PROC_OPEN
#define ET_PROC_OPEN 1
Process has opened ET system (has access to mapped memory).
ET_PROCESSES_MAX
#define ET_PROCESSES_MAX ET_ATTACHMENTS_MAX
Maximum number of local processes allowed to open the system.
ET_PSTAT2ET
#define ET_PSTAT2ET (p, offset) ((et_station *)((char *)(p) - (offset)))
Macro to change station pointer from user space to ET system space.
ET_PSTAT2USR
#define ET_PSTAT2USR (p, offset) ((et_station *)((char *)(p) + (offset)))
Macro to change station pointer from ET system space to user space.
ET_SET_BIT64
#define ET_SET_BIT64 (x) ((x) | ET_BIT64_MASK)
Set the bit in the bitInfo word identifying ET system's host as running a 64-bit OS.
ET_SET_KILL
#define ET_SET_KILL (x) ((x) | ET_KILL_MASK)
Set the bit in the bitInfo word telling ET system to kill itself ASAP.
ET_STRUCT_NEW
#define ET_STRUCT_NEW 0
Structure is newly created and not yet initialized.
ET_STRUCT_OK
#define ET_STRUCT_OK 1
Structure is initialized and ready for use.
ET_SYSTEM_TYPE_C
#define ET_SYSTEM_TYPE_C 1
ET system implemented through C language library.
ET_SYSTEM_TYPE_JAVA
#define ET_SYSTEM_TYPE_JAVA 2
ET system implemented through Java language library.
ET_THREAD_KEEP
#define ET_THREAD_KEEP 0
Keep thread around.
ET_THREAD_KILL
#define ET_THREAD_KILL 1
Kill thread.
ET_VERSION
#define ET_VERSION 16
Major version number.
ET_VERSION_MINOR
#define ET_VERSION_MINOR 5
Minor version number.
Typedef Documentation
et_bridge_config
typedef struct et_bridge_config_t et_bridge_config
Structure to define configuration parameters used to bridge ET systems (transfer events between 2 systems).
et_id
typedef struct et_id_t et_id
Structure defining an ET system user id (one needed for each system in use) which contains pointers to key mem locations, config info, status info, node locality and remote node info.
et_list
typedef struct et_list_t et_list
Structure defining a station's input or output list of events.
et_mem
typedef struct et_mem_t et_mem
Structure containing info stored at front of shared or mapped memory.
et_netthread
typedef struct et_netthread_t et_netthread
Struct for passing data from system to network threads.
et_open_config
typedef struct et_open_config_t et_open_config
Structure holding all configuration parameters used to open an ET system.
et_response
typedef struct et_response_t et_response
Structure for holding an ET system's single response to ET client's broad/multicast.
ET_SELECT_FUNCPTR
typedef int(* ET_SELECT_FUNCPTR) (void *, et_stat_id, et_event *)
Defines event selection function.
et_stat_config
typedef struct et_stat_config_t et_stat_config
Structure to hold parameters used to configure a station.
et_stat_data
typedef struct et_stat_data_t et_stat_data
Structure to hold the current state of a station.
et_station
typedef struct et_station_t et_station
Structure defining a station.
et_sys_config
typedef struct et_sys_config_t et_sys_config
Structure containing all info necessary to configure an ET system.
et_system
typedef struct et_system_t et_system
Structure containing all ET system information.
Function Documentation
et_cast_thread()
void* et_cast_thread (void * arg)
et_findlocality()
int et_findlocality (const char * filename, et_openconfig openconfig)
This routine determines whether we are looking for the ET system locally, locally on some non-pthread-mutex-sharing operating system, or remotely.
Parameters
filename name of ET system file.
openconfig ET system open configuration.
Returns
ET_REMOTE if looking for a remote ET system.
ET_LOCAL if looking for a local ET system.
ET_LOCAL_NOSHARE if looking for a local ET system without pthread mutex sharing.
References ET_DEBUG_NONE, ET_ERROR, ET_ERROR_TIMEOUT, ET_ERROR_TOOMANY, et_findserver2(), ET_HOST_ANYWHERE, ET_HOST_AS_REMOTE, ET_HOST_LOCAL, ET_HOST_REMOTE, ET_IPADDRSTRLEN, ET_LOCAL, ET_LOCAL_NOSHARE, et_logmsg(), ET_MUTEX_SHARE, ET_REMOTE, et_sharedmutex(), et_open_config_t::host, and et_open_config_t::mode.
Referenced by et_open().
et_findserver()
int et_findserver (const char * etname, char * ethost, int * port, uint32_t * inetaddr, et_open_config * config, et_response ** allETinfo, int debug)
Referenced by etr_open().
et_flush_events()
void et_flush_events (et_id * id, et_att_id att, et_stat_id stat_id)
Referenced by et_station_detach().
et_id_destroy()
void et_id_destroy (et_sys_id id)
Referenced by et_open(), etr_close(), etr_forcedclose(), and etr_kill().
et_id_init()
int et_id_init (et_sys_id * id)
Referenced by et_open(), and et_system_start().
et_init_attachment()
void et_init_attachment (et_system * sys, et_att_id id)
Referenced by et_station_attach().
et_init_event()
void et_init_event (et_event * pe)
Referenced by etr_event_get(), etr_event_new(), etr_events_get(), etr_events_new(), and etr_events_new_group().
et_init_event_()
void et_init_event_ (et_event * pe)
et_init_histogram()
void et_init_histogram (et_id * id)
et_init_llist()
void et_init_llist (et_list * pl)
et_init_process()
void et_init_process (et_system * sys, et_proc_id id)
et_init_station()
void et_init_station (et_station * ps)
Referenced by et_station_create_at().
et_init_stats_all()
void et_init_stats_all (et_id * id)
et_init_stats_allatts()
void et_init_stats_allatts (et_system * sys)
et_init_stats_allstations()
void et_init_stats_allstations (et_id * id)
et_init_stats_att()
void et_init_stats_att (et_system * sys, et_att_id id)
et_init_stats_station()
void et_init_stats_station (et_station * ps)
et_llist_lock()
void et_llist_lock (et_list * pl)
Referenced by et_station_setcue(), et_station_setprescale(), and et_station_setselectwords().
et_llist_read()
int et_llist_read (et_list * pl, et_event ** pe)
et_llist_unlock()
void et_llist_unlock (et_list * pl)
Referenced by et_station_setcue(), et_station_setprescale(), and et_station_setselectwords().
et_llist_write()
int et_llist_write (et_id * id, et_list * pl, et_event ** pe, int num)
et_llist_write_gc()
int et_llist_write_gc (et_id * id, et_event ** pe, int num)
et_logmsg()
void et_logmsg (char * sev, char * fmt, ...)
Referenced by et_attach_geteventsdump(), et_attach_geteventsget(), et_attach_geteventsmake(), et_attach_geteventsput(), et_event_dump(), et_event_get(), et_event_new(), et_event_put(), et_event_setdatabuffer(), et_events_bridge(), et_events_dump(), et_events_get(), et_events_new(), et_events_new_group(), et_events_put(), et_fifo_getEntry(), et_fifo_getEntryTO(), et_fifo_newEntry(), et_fifo_newEntryTO(), et_findlocality(), et_open(), et_station_attach(), et_station_compare_parallel(), et_station_config_check(), et_station_create_at(), et_station_detach(), et_station_exists(), et_station_getattachments(), et_station_getblock(), et_station_getclass(), et_station_getcue(), et_station_getfunction(), et_station_getinputcount(), et_station_getlib(), et_station_getoutputcount(), et_station_getposition(), et_station_getprescale(), et_station_getrestore(), et_station_getselect(), et_station_getselectwords(), et_station_getstatus(), et_station_getuser(), et_station_isattached(), et_station_remove(), et_station_setblock(), et_station_setcue(), et_station_setposition(), et_station_setprescale(), et_station_setrestore(), et_station_setselectwords(), et_station_setuser(), et_system_close(), et_wakeup_all(), et_wakeup_attachment(), etr_alive(), etr_close(), etr_event_dump(), etr_event_get(), etr_event_new(), etr_event_put(), etr_events_dump(), etr_events_get(), etr_events_new(), etr_events_new_group(), etr_events_put(), etr_forcedclose(), etr_kill(), etr_open(), etr_station_attach(), etr_station_create_at(), etr_station_detach(), etr_station_exists(), etr_station_getclass(), etr_station_getfunction(), etr_station_getlib(), etr_station_getposition(), etr_station_getselectwords(), etr_station_isattached(), etr_station_remove(), etr_station_setposition(), etr_station_setselectwords(), etr_wait_for_alive(), etr_wakeup_all(), and etr_wakeup_attachment().
et_look()
int et_look (et_sys_id * id, const char * filename)
et_mem_attach()
int et_mem_attach (const char * name, void ** pmemory, et_mem * pInfo)
et_mem_create()
int et_mem_create (const char * name, size_t memsize, void ** pmemory, size_t * totalSize)
et_mem_remove()
int et_mem_remove (const char * name, void * pmem)
et_mem_size()
int et_mem_size (const char * name, size_t * totalsize, size_t * usedsize)
et_mem_unlock()
void et_mem_unlock (et_id * id)
Referenced by et_attach_geteventsdump(), et_attach_geteventsget(), et_attach_geteventsmake(), et_attach_geteventsput(), et_event_dump(), et_event_get(), et_event_new(), et_event_put(), et_events_dump(), et_events_get(), et_events_new(), et_events_new_group(), et_events_put(), et_station_attach(), et_station_create_at(), et_station_detach(), et_station_exists(), et_station_getattachments(), et_station_getblock(), et_station_getclass(), et_station_getcue(), et_station_getfunction(), et_station_getinputcount(), et_station_getlib(), et_station_getoutputcount(), et_station_getposition(), et_station_getprescale(), et_station_getrestore(), et_station_getselect(), et_station_getselectwords(), et_station_getstatus(), et_station_getuser(), et_station_isattached(), et_station_remove(), et_station_setblock(), et_station_setcue(), et_station_setposition(), et_station_setprescale(), et_station_setrestore(), et_station_setselectwords(), et_station_setuser(), et_wakeup_all(), and et_wakeup_attachment().
et_mem_unmap()
int et_mem_unmap (const char * name, void * pmem)
et_mem_write_first_block()
void et_mem_write_first_block (char * ptr, uint32_t headerByteSize, uint64_t eventByteSize, uint64_t headerPosition, uint64_t dataPosition, uint64_t totalByteSize, uint64_t usedByteSize)
et_memRead_lock()
void et_memRead_lock (et_id * id)
Referenced by et_attach_geteventsdump(), et_attach_geteventsget(), et_attach_geteventsmake(), et_attach_geteventsput(), et_event_dump(), et_event_get(), et_event_new(), et_event_put(), et_events_dump(), et_events_get(), et_events_new(), et_events_new_group(), et_events_put(), et_station_attach(), et_station_create_at(), et_station_exists(), et_station_getattachments(), et_station_getblock(), et_station_getclass(), et_station_getcue(), et_station_getfunction(), et_station_getinputcount(), et_station_getlib(), et_station_getoutputcount(), et_station_getposition(), et_station_getprescale(), et_station_getrestore(), et_station_getselect(), et_station_getselectwords(), et_station_getstatus(), et_station_getuser(), et_station_isattached(), et_station_remove(), et_station_setblock(), et_station_setcue(), et_station_setposition(), et_station_setprescale(), et_station_setrestore(), et_station_setselectwords(), et_station_setuser(), et_wakeup_all(), and et_wakeup_attachment().
et_memWrite_lock()
void et_memWrite_lock (et_id * id)
Referenced by et_station_detach().
et_mutex_locked()
int et_mutex_locked (pthread_mutex_t * pmutex)
et_netserver()
void* et_netserver (void * arg)
et_repair_gc()
int et_repair_gc (et_id * id)
et_repair_station()
int et_repair_station (et_id * id, et_stat_id stat_id)
et_responds()
int et_responds (const char * etname)
et_restore_events()
int et_restore_events (et_id * id, et_att_id att, et_stat_id stat_id)
Referenced by et_station_detach().
et_sharedmutex()
int et_sharedmutex (void)
Referenced by et_findlocality(), and et_open().
et_station_compare_parallel()
int et_station_compare_parallel (et_id * id, et_stat_config * group, et_stat_config * config)
This routine compares all relevant station configuration parameters to see if both configs are compatible enough to belong in the same parallel station group.
Parameters
id et system id.
group pointer to config of a station already in a parallel group.
config pointer to config of station to add to parallel group.
Returns
1 if compatible.
0 if NOT compatible.
References et_stat_config_t::block_mode, et_id_t::debug, ET_DEBUG_ERROR, et_logmsg(), ET_STATION_SELECT_EQUALCUE, ET_STATION_SELECT_RROBIN, et_stat_config_t::flow_mode, et_stat_config_t::prescale, and et_stat_config_t::select_mode.
et_station_config_check()
int et_station_config_check (et_id * id, et_stat_config * sc)
This routine checks a station's configuration settings for internal inconsistencies or bad values.
Parameters
id et system id.
sc station config pointer.
Returns
ET_OK if successful.
ET_ERROR if there is an internal inconsistency or bad value in the configuration.
References et_stat_config_t::block_mode, et_system_t::config, et_stat_config_t::cue, et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR, et_logmsg(), ET_OK, ET_STATION_BLOCKING, ET_STATION_NONBLOCKING, ET_STATION_PARALLEL, ET_STATION_RESTORE_GC, ET_STATION_RESTORE_IN, ET_STATION_RESTORE_OUT, ET_STATION_RESTORE_REDIST, ET_STATION_SELECT_ALL, ET_STATION_SELECT_EQUALCUE, ET_STATION_SELECT_MATCH, ET_STATION_SELECT_RROBIN, ET_STATION_SELECT_USER, ET_STATION_SERIAL, et_stat_config_t::flow_mode, et_stat_config_t::fname, et_stat_config_t::lib, et_sys_config_t::nattachments, et_sys_config_t::nevents, et_stat_config_t::prescale, et_stat_config_t::restore_mode, et_stat_config_t::select_mode, et_id_t::sys, and et_stat_config_t::user_mode.
Referenced by et_station_create_at().
et_station_dump()
int et_station_dump (et_id * id, et_event * pe)
Referenced by et_event_dump().
et_station_lock()
void et_station_lock (et_system * sys)
Referenced by et_station_attach(), et_station_create_at(), et_station_detach(), et_station_getposition(), et_station_remove(), et_station_setblock(), et_station_setcue(), et_station_setposition(), et_station_setprescale(), et_station_setrestore(), et_station_setselectwords(), and et_station_setuser().
et_station_ndump()
int et_station_ndump (et_id * id, et_event * pe[], int num)
Referenced by et_events_dump().
et_station_nread()
int et_station_nread (et_id * id, et_stat_id stat_id, et_event * pe[], int mode, et_att_id att, struct timespec * time, int num, int * nread)
Referenced by et_events_get(), and et_events_new().
et_station_nread_group()
int et_station_nread_group (et_id * id, et_stat_id stat_id, et_event * pe[], int mode, et_att_id att, struct timespec * time, int num, int group, int * nread)
Referenced by et_events_new_group().
et_station_nwrite()
int et_station_nwrite (et_id * id, et_stat_id stat_id, et_event * pe[], int num)
Referenced by et_events_put().
et_station_read()
int et_station_read (et_id * id, et_stat_id stat_id, et_event ** pe, int _mode, et_att_id att, struct timespec * time)
Referenced by et_event_get(), and et_event_new().
et_station_unlock()
void et_station_unlock (et_system * sys)
Referenced by et_station_attach(), et_station_create_at(), et_station_detach(), et_station_getposition(), et_station_remove(), et_station_setblock(), et_station_setcue(), et_station_setposition(), et_station_setprescale(), et_station_setrestore(), et_station_setselectwords(), and et_station_setuser().
et_station_write()
int et_station_write (et_id * id, et_stat_id stat_id, et_event * pe)
Referenced by et_event_put().
et_system_lock()
void et_system_lock (et_system * sys)
Referenced by et_event_dump(), et_events_dump(), et_station_attach(), and et_station_detach().
et_system_unlock()
void et_system_unlock (et_system * sys)
Referenced by et_event_dump(), et_events_dump(), et_station_attach(), and et_station_detach().
et_tcp_lock()
void et_tcp_lock (et_id * id)
Referenced by etr_alive(), etr_close(), etr_event_dump(), etr_event_get(), etr_event_new(), etr_event_put(), etr_events_dump(), etr_events_get(), etr_events_new(), etr_events_new_group(), etr_events_put(), etr_forcedclose(), etr_kill(), etr_station_attach(), etr_station_create_at(), etr_station_detach(), etr_station_exists(), etr_station_getclass(), etr_station_getfunction(), etr_station_getlib(), etr_station_getposition(), etr_station_getselectwords(), etr_station_isattached(), etr_station_remove(), etr_station_setposition(), etr_station_setselectwords(), etr_wait_for_alive(), etr_wakeup_all(), and etr_wakeup_attachment().
et_tcp_unlock()
void et_tcp_unlock (et_id * id)
Referenced by etr_alive(), etr_close(), etr_event_dump(), etr_event_get(), etr_event_new(), etr_event_put(), etr_events_dump(), etr_events_get(), etr_events_new(), etr_events_new_group(), etr_events_put(), etr_forcedclose(), etr_kill(), etr_station_attach(), etr_station_create_at(), etr_station_detach(), etr_station_exists(), etr_station_getclass(), etr_station_getfunction(), etr_station_getlib(), etr_station_getposition(), etr_station_getselectwords(), etr_station_isattached(), etr_station_remove(), etr_station_setposition(), etr_station_setselectwords(), etr_wait_for_alive(), etr_wakeup_all(), and etr_wakeup_attachment().
et_temp_attach()
void* et_temp_attach (const char * name, size_t size)
Referenced by et_event_get(), and et_events_get().
et_temp_create()
void* et_temp_create (const char * name, size_t size)
et_temp_remove()
int et_temp_remove (const char * name, void * pmem, size_t size)
Referenced by et_event_dump(), and et_events_dump().
et_transfer_lock()
void et_transfer_lock (et_station * ps)
et_transfer_lock_all()
void et_transfer_lock_all (et_id * id)
Referenced by et_station_attach(), et_station_create_at(), et_station_detach(), et_station_getposition(), et_station_remove(), and et_station_setposition().
et_transfer_unlock()
void et_transfer_unlock (et_station * ps)
et_transfer_unlock_all()
void et_transfer_unlock_all (et_id * id)
Referenced by et_station_attach(), and et_station_detach().
et_unlook()
int et_unlook (et_sys_id id)
et_wait_for_system()
int et_wait_for_system (et_sys_id id, struct timespec * timeout, const char * etname)
etl_alive()
int etl_alive (et_sys_id id)
Referenced by et_alive().
etl_close()
int etl_close (et_sys_id id)
Referenced by et_close().
etl_forcedclose()
int etl_forcedclose (et_sys_id id)
Referenced by et_forcedclose().
etl_kill()
int etl_kill (et_sys_id id)
Referenced by et_kill().
etl_open()
int etl_open (et_sys_id * id, const char * filename, et_openconfig openconfig)
Referenced by et_open().
etl_wait_for_alive()
int etl_wait_for_alive (et_sys_id id)
Referenced by et_wait_for_alive().
etn_alive()
int etn_alive (et_sys_id id)
Referenced by et_alive().
etn_close()
int etn_close (et_sys_id id)
Referenced by et_close().
etn_event_dump()
int etn_event_dump (et_sys_id id, et_att_id att, et_event * ev)
Referenced by et_event_dump().
etn_event_get()
int etn_event_get (et_sys_id id, et_att_id att, et_event ** ev, int mode, struct timespec * deltatime)
Referenced by et_event_get().
etn_event_new()
int etn_event_new (et_sys_id id, et_att_id att, et_event ** ev, int mode, struct timespec * deltatime, size_t size)
Referenced by et_event_new().
etn_event_put()
int etn_event_put (et_sys_id id, et_att_id att, et_event * ev)
Referenced by et_event_put().
etn_events_dump()
int etn_events_dump (et_sys_id id, et_att_id att, et_event * evs[], int num)
Referenced by et_events_dump().
etn_events_get()
int etn_events_get (et_sys_id id, et_att_id att, et_event * evs[], int mode, struct timespec * deltatime, int num, int * nread)
Referenced by et_events_get().
etn_events_new()
int etn_events_new (et_sys_id id, et_att_id att, et_event * evs[], int mode, struct timespec * deltatime, size_t size, int num, int * nread)
Referenced by et_events_new().
etn_events_new_group()
int etn_events_new_group (et_sys_id id, et_att_id att, et_event * evs[], int mode, struct timespec * deltatime, size_t size, int num, int group, int * nread)
Referenced by et_events_new_group().
etn_events_put()
int etn_events_put (et_sys_id id, et_att_id att, et_event * evs[], int num)
Referenced by et_events_put().
etn_forcedclose()
int etn_forcedclose (et_sys_id id)
Referenced by et_forcedclose().
etn_kill()
int etn_kill (et_sys_id id)
Referenced by et_kill().
etn_open()
int etn_open (et_sys_id * id, const char * filename, et_openconfig openconfig)
Referenced by et_open().
etn_wait_for_alive()
int etn_wait_for_alive (et_sys_id id)
Referenced by et_wait_for_alive().
etr_alive()
int etr_alive (et_sys_id id)
References et_id_t::debug, ET_DEBUG_ERROR, et_logmsg(), ET_NET_ALIVE, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_alive().
etr_attach_geteventsdump()
int etr_attach_geteventsdump (et_sys_id id, et_att_id att_id, uint64_t * events)
Referenced by et_attach_geteventsdump().
etr_attach_geteventsget()
int etr_attach_geteventsget (et_sys_id id, et_att_id att_id, uint64_t * events)
Referenced by et_attach_geteventsget().
etr_attach_geteventsmake()
int etr_attach_geteventsmake (et_sys_id id, et_att_id att_id, uint64_t * events)
Referenced by et_attach_geteventsmake().
etr_attach_geteventsput()
int etr_attach_geteventsput (et_sys_id id, et_att_id att_id, uint64_t * events)
Referenced by et_attach_geteventsput().
etr_close()
int etr_close (et_sys_id id)
References et_id_t::debug, ET_DEBUG_ERROR, et_id_destroy(), et_logmsg(), ET_NET_CLOSE, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_close().
etr_event_dump()
int etr_event_dump (et_sys_id id, et_att_id att, et_event * ev)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_EV_DUMP, ET_OK, et_tcp_lock(), et_tcp_unlock(), et_event_t::modify, et_event_t::pdata, et_event_t::place, and et_id_t::sockfd.
Referenced by et_event_dump().
etr_event_get()
int etr_event_get (et_sys_id id, et_att_id att, et_event ** ev, int wait, struct timespec * deltatime)
References et_id_t::bit64, et_event_t::byteorder, et_event_t::control, et_event_t::datastatus, et_id_t::debug, ET_64BIT_UINT, ET_DATA_MASK, ET_DATA_SHIFT, ET_DEBUG_ERROR, ET_DUMP, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_TIMEOUT, ET_ERROR_WRITE, et_init_event(), et_logmsg(), ET_MODIFY, ET_MODIFY_HEADER, ET_NET_EV_GET, ET_OK, ET_PRIORITY_MASK, ET_SLEEP, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), ET_TIMED, ET_WAIT_MASK, et_event_t::length, et_event_t::memsize, et_event_t::modify, et_event_t::pdata, et_event_t::place, et_event_t::priority, and et_id_t::sockfd.
Referenced by et_event_get().
etr_event_new()
int etr_event_new (et_sys_id id, et_att_id att, et_event ** ev, int mode, struct timespec * deltatime, size_t size)
References et_id_t::bit64, et_id_t::debug, et_id_t::esize, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_TIMEOUT, ET_ERROR_WRITE, ET_EVENT_TEMP, ET_HIGHINT, et_init_event(), et_logmsg(), ET_LOWINT, ET_MODIFY, ET_NET_EV_NEW, ET_NOALLOC, ET_OK, ET_SLEEP, et_tcp_lock(), et_tcp_unlock(), ET_TIMED, ET_WAIT_MASK, et_event_t::length, et_event_t::memsize, et_event_t::modify, et_event_t::owner, et_event_t::pdata, et_event_t::place, et_id_t::sockfd, and et_event_t::temp.
Referenced by et_event_new().
etr_event_put()
int etr_event_put (et_sys_id id, et_att_id att, et_event * ev)
References et_event_t::byteorder, et_event_t::control, et_event_t::datastatus, et_id_t::debug, ET_DATA_SHIFT, ET_DEBUG_ERROR, ET_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_WRITE, ET_HIGHINT, et_logmsg(), ET_LOWINT, ET_MODIFY, ET_NET_EV_PUT, ET_NOALLOC, ET_OK, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), et_event_t::length, et_event_t::memsize, et_event_t::modify, et_event_t::owner, et_event_t::pdata, et_event_t::place, et_event_t::priority, and et_id_t::sockfd.
Referenced by et_event_put().
etr_events_dump()
int etr_events_dump (et_sys_id id, et_att_id att, et_event * evs[], int num)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_WRITE, et_logmsg(), ET_NET_EVS_DUMP, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_events_dump().
etr_events_get()
int etr_events_get (et_sys_id id, et_att_id att, et_event * evs[], int wait, struct timespec * deltatime, int num, int * nread)
References et_id_t::bit64, et_event_t::byteorder, et_event_t::control, et_event_t::datastatus, et_id_t::debug, ET_64BIT_UINT, ET_DATA_MASK, ET_DATA_SHIFT, ET_DEBUG_ERROR, ET_DUMP, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_TIMEOUT, ET_ERROR_WRITE, et_init_event(), et_logmsg(), ET_MODIFY, ET_MODIFY_HEADER, ET_NET_EVS_GET, ET_OK, ET_PRIORITY_MASK, ET_SLEEP, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), ET_TIMED, ET_WAIT_MASK, et_event_t::length, et_event_t::memsize, et_event_t::modify, et_event_t::place, et_event_t::priority, and et_id_t::sockfd.
Referenced by et_events_get().
etr_events_new()
int etr_events_new (et_sys_id id, et_att_id att, et_event * evs[], int mode, struct timespec * deltatime, size_t size, int num, int * nread)
References et_id_t::bit64, et_id_t::debug, et_id_t::esize, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_TIMEOUT, ET_ERROR_WRITE, ET_EVENT_NORMAL, ET_EVENT_TEMP, ET_HIGHINT, et_init_event(), et_logmsg(), ET_LOWINT, ET_MODIFY, ET_NET_EVS_NEW, ET_NOALLOC, ET_OK, ET_SLEEP, et_tcp_lock(), et_tcp_unlock(), ET_TIMED, ET_WAIT_MASK, et_event_t::length, et_event_t::memsize, et_event_t::modify, et_event_t::owner, et_event_t::place, et_id_t::sockfd, and et_event_t::temp.
Referenced by et_events_new().
etr_events_new_group()
int etr_events_new_group (et_sys_id id, et_att_id att, et_event * evs[], int mode, struct timespec * deltatime, size_t size, int num, int group, int * nread)
References et_id_t::bit64, et_id_t::debug, et_id_t::esize, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_TIMEOUT, ET_ERROR_WRITE, ET_EVENT_NORMAL, ET_EVENT_TEMP, ET_HIGHINT, et_init_event(), et_logmsg(), ET_LOWINT, ET_MODIFY, ET_NET_EVS_NEW_GRP, ET_NOALLOC, ET_OK, ET_SLEEP, et_tcp_lock(), et_tcp_unlock(), ET_TIMED, ET_WAIT_MASK, et_event_t::length, et_event_t::memsize, et_event_t::modify, et_event_t::owner, et_event_t::place, et_id_t::sockfd, and et_event_t::temp.
Referenced by et_events_new_group().
etr_events_put()
int etr_events_put (et_sys_id id, et_att_id att, et_event * evs[], int num)
References et_event_t::byteorder, et_id_t::debug, ET_DATA_SHIFT, ET_DEBUG_ERROR, ET_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_WRITE, ET_HIGHINT, et_logmsg(), ET_LOWINT, ET_MODIFY, ET_NET_EVS_PUT, ET_NOALLOC, ET_OK, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), et_event_t::length, et_event_t::pdata, and et_id_t::sockfd.
Referenced by et_events_put().
etr_forcedclose()
int etr_forcedclose (et_sys_id id)
References et_id_t::debug, ET_DEBUG_ERROR, et_id_destroy(), et_logmsg(), ET_NET_FCLOSE, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_forcedclose().
etr_kill()
int etr_kill (et_sys_id id)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_WRITE, et_id_destroy(), et_logmsg(), ET_NET_KILL, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_kill().
etr_open()
int etr_open (et_sys_id * id, const char * et_filename, et_openconfig openconfig)
References et_id_t::bit64, et_open_config_t::cast, et_open_config_t::debug_default, et_id_t::endian, et_id_t::esize, ET_64BIT_UINT, ET_DEBUG_ERROR, ET_DEBUG_INFO, ET_DIRECT, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_TIMEOUT, ET_ERROR_TOOMANY, ET_ERROR_WRITE, et_findserver(), et_freeAnswers(), ET_HOST_LOCAL, ET_IOV_MAX, et_logmsg(), ET_MAGIC_INT1, ET_MAGIC_INT2, ET_MAGIC_INT3, ET_MAXHOSTNAMELEN, ET_OK, ET_OPEN_NOWAIT, et_orderIpAddrs(), ET_REMOTE, et_id_t::ethost, et_open_config_t::host, et_open_config_t::interface, et_id_t::iov_max, et_id_t::lang, et_id_t::localAddr, et_id_t::locality, et_open_config_t::netinfo, et_id_t::nevents, et_id_t::nselects, et_id_t::port, et_open_config_t::serverport, et_id_t::sockfd, et_id_t::systemendian, et_open_config_t::tcpNoDelay, et_open_config_t::tcpRecvBufSize, et_open_config_t::tcpSendBufSize, et_open_config_t::timeout, et_id_t::version, and et_open_config_t::wait.
Referenced by et_open().
etr_station_attach()
int etr_station_attach (et_sys_id id, et_stat_id stat_id, et_att_id * att)
References et_id_t::debug, ET_DEBUG_ERROR, ET_DEBUG_WARN, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_WRITE, ET_IPADDRSTRLEN, et_logmsg(), ET_MAXHOSTNAMELEN, ET_NET_STAT_ATT, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_attach().
etr_station_create()
int etr_station_create (et_sys_id id, et_stat_id * stat_id, const char * stat_name, et_statconfig sconfig)
References ET_END, and etr_station_create_at().
etr_station_create_at()
int etr_station_create_at (et_sys_id id, et_stat_id * stat_id, const char * stat_name, et_statconfig sconfig, int position, int parallelposition)
References et_stat_config_t::block_mode, et_stat_config_t::classs, et_stat_config_t::cue, et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_EXISTS, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_CRAT, ET_OK, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), et_stat_config_t::flow_mode, et_stat_config_t::fname, et_stat_config_t::init, et_stat_config_t::lib, et_stat_config_t::prescale, et_stat_config_t::restore_mode, et_stat_config_t::select, et_stat_config_t::select_mode, et_id_t::sockfd, and et_stat_config_t::user_mode.
Referenced by et_station_create_at(), and etr_station_create().
etr_station_detach()
int etr_station_detach (et_sys_id id, et_att_id att)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_DET, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_detach().
etr_station_exists()
int etr_station_exists (et_sys_id id, et_stat_id * stat_id, const char * stat_name)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_REMOTE, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_EX, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_exists().
etr_station_getattachments()
int etr_station_getattachments (et_sys_id id, et_stat_id stat_id, int * numatts)
Referenced by et_station_getattachments().
etr_station_getblock()
int etr_station_getblock (et_sys_id id, et_stat_id stat_id, int * block)
Referenced by et_station_getblock().
etr_station_getclass()
int etr_station_getclass (et_sys_id id, et_stat_id stat_id, char * classs)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, ET_FILENAME_LENGTH, et_logmsg(), ET_NET_STAT_CLASS, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_getclass().
etr_station_getcue()
int etr_station_getcue (et_sys_id id, et_stat_id stat_id, int * cue)
Referenced by et_station_getcue().
etr_station_getfunction()
int etr_station_getfunction (et_sys_id id, et_stat_id stat_id, char * function)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, ET_FUNCNAME_LENGTH, et_logmsg(), ET_NET_STAT_FUNC, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_getfunction().
etr_station_getinputcount()
int etr_station_getinputcount (et_sys_id id, et_stat_id stat_id, int * cnt)
Referenced by et_station_getinputcount().
etr_station_getlib()
int etr_station_getlib (et_sys_id id, et_stat_id stat_id, char * lib)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, ET_FILENAME_LENGTH, et_logmsg(), ET_NET_STAT_LIB, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_getlib().
etr_station_getoutputcount()
int etr_station_getoutputcount (et_sys_id id, et_stat_id stat_id, int * cnt)
Referenced by et_station_getoutputcount().
etr_station_getposition()
int etr_station_getposition (et_sys_id id, et_stat_id stat_id, int * position, int * parallelposition)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_GPOS, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_getposition().
etr_station_getprescale()
int etr_station_getprescale (et_sys_id id, et_stat_id stat_id, int * prescale)
Referenced by et_station_getprescale().
etr_station_getrestore()
int etr_station_getrestore (et_sys_id id, et_stat_id stat_id, int * restore)
Referenced by et_station_getrestore().
etr_station_getselect()
int etr_station_getselect (et_sys_id id, et_stat_id stat_id, int * select)
Referenced by et_station_getselect().
etr_station_getselectwords()
int etr_station_getselectwords (et_sys_id id, et_stat_id stat_id, int select[])
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_GSW, ET_OK, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_getselectwords().
etr_station_getstatus()
int etr_station_getstatus (et_sys_id id, et_stat_id stat_id, int * status)
Referenced by et_station_getstatus().
etr_station_getuser()
int etr_station_getuser (et_sys_id id, et_stat_id stat_id, int * user)
Referenced by et_station_getuser().
etr_station_isattached()
int etr_station_isattached (et_sys_id id, et_stat_id stat_id, et_att_id att)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_ISAT, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_isattached().
etr_station_remove()
int etr_station_remove (et_sys_id id, et_stat_id stat_id)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_RM, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_remove().
etr_station_setblock()
int etr_station_setblock (et_sys_id id, et_stat_id stat_id, int block)
Referenced by et_station_setblock().
etr_station_setcue()
int etr_station_setcue (et_sys_id id, et_stat_id stat_id, int cue)
Referenced by et_station_setcue().
etr_station_setposition()
int etr_station_setposition (et_sys_id id, et_stat_id stat_id, int position, int parallelposition)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_SPOS, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_setposition().
etr_station_setprescale()
int etr_station_setprescale (et_sys_id id, et_stat_id stat_id, int prescale)
Referenced by et_station_setprescale().
etr_station_setrestore()
int etr_station_setrestore (et_sys_id id, et_stat_id stat_id, int restore)
Referenced by et_station_setrestore().
etr_station_setselectwords()
int etr_station_setselectwords (et_sys_id id, et_stat_id stat_id, int select[])
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_STAT_SSW, ET_STATION_SELECT_INTS, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_station_setselectwords().
etr_station_setuser()
int etr_station_setuser (et_sys_id id, et_stat_id stat_id, int user)
Referenced by et_station_setuser().
etr_system_getattachments()
int etr_system_getattachments (et_sys_id id, int * atts)
Referenced by et_system_getattachments().
etr_system_getattsmax()
int etr_system_getattsmax (et_sys_id id, int * attsmax)
Referenced by et_system_getattsmax().
etr_system_getgroupcount()
int etr_system_getgroupcount (et_sys_id id, int * groupCnt)
Referenced by et_system_setgroup().
etr_system_getheartbeat()
int etr_system_getheartbeat (et_sys_id id, int * heartbeat)
Referenced by et_system_getheartbeat().
etr_system_getpid()
int etr_system_getpid (et_sys_id id, int * pid)
Referenced by et_system_getpid().
etr_system_getprocs()
int etr_system_getprocs (et_sys_id id, int * procs)
Referenced by et_system_getprocs().
etr_system_getprocsmax()
int etr_system_getprocsmax (et_sys_id id, int * procsmax)
Referenced by et_system_getprocsmax().
etr_system_getstations()
int etr_system_getstations (et_sys_id id, int * stations)
Referenced by et_system_getstations().
etr_system_getstationsmax()
int etr_system_getstationsmax (et_sys_id id, int * stationsmax)
Referenced by et_system_getstationsmax().
etr_system_gettemps()
int etr_system_gettemps (et_sys_id id, int * temps)
Referenced by et_system_gettemps().
etr_system_gettempsmax()
int etr_system_gettempsmax (et_sys_id id, int * tempsmax)
Referenced by et_system_gettempsmax().
etr_wait_for_alive()
int etr_wait_for_alive (et_sys_id id)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_READ, ET_ERROR_WRITE, et_logmsg(), ET_NET_WAIT, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_wait_for_alive().
etr_wakeup_all()
int etr_wakeup_all (et_sys_id id, et_stat_id stat_id)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_WRITE, et_logmsg(), ET_NET_WAKE_ALL, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_wakeup_all().
etr_wakeup_attachment()
int etr_wakeup_attachment (et_sys_id id, et_att_id att)
References et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR_WRITE, et_logmsg(), ET_NET_WAKE_ATT, ET_OK, et_tcp_lock(), et_tcp_unlock(), and et_id_t::sockfd.
Referenced by et_wakeup_attachment().