ET System: et_statconfig.c File Reference
et_statconfig.c File Reference
#include <stdio.h>
#include <string.h>
#include "et_private.h"
Functions
int et_station_config_init (et_statconfig *sconfig)
This routine initializes a configuration used to create a station in the ET system.
int et_station_config_destroy (et_statconfig sconfig)
This routine frees the memory allocated when a configuration is initialized by et_station_config_init().
int et_station_config_setblock (et_statconfig sconfig, int val)
This routine sets a station configuration's block mode.
int et_station_config_getblock (et_statconfig sconfig, int *val)
This routine gets a station configuration's block mode.
int et_station_config_setflow (et_statconfig sconfig, int val)
This routine sets a station configuration's flow mode.
int et_station_config_getflow (et_statconfig sconfig, int *val)
This routine gets a station configuration's flow mode.
int et_station_config_setselect (et_statconfig sconfig, int val)
This routine sets a station configuration's select mode which determines the algorithm this station uses to decide which events to let into its input list.
int et_station_config_getselect (et_statconfig sconfig, int *val)
This routine gets a station configuration's select mode.
int et_station_config_setuser (et_statconfig sconfig, int val)
This routine sets a station configuration's user mode which is the maximum number of users which may simultaneously attach to the station.
int et_station_config_getuser (et_statconfig sconfig, int *val)
This routine gets a station configuration's user mode.
int et_station_config_setrestore (et_statconfig sconfig, int val)
This routine sets a station configuration's restore mode which determines where events go when the attachment that owns those events detaches from the station.
int et_station_config_getrestore (et_statconfig sconfig, int *val)
This routine gets a station configuration's restore mode which determines where events go when the attachment who owns those events detaches from the station.
int et_station_config_setcue (et_statconfig sconfig, int val)
This routine sets a station configuration's queue size which is the max number of events allowed in the input list when the station is nonblocking.
int et_station_config_getcue (et_statconfig sconfig, int *val)
This routine gets a station configuration's queue size which is the max number of events allowed in the input list when the station is nonblocking.
int et_station_config_setprescale (et_statconfig sconfig, int val)
This routine sets a station configuration's prescale value.
int et_station_config_getprescale (et_statconfig sconfig, int *val)
This routine gets a station configuration's prescale value.
int et_station_config_setselectwords (et_statconfig sconfig, int val[])
This routine sets a station configuration's array of selection integers.
int et_station_config_getselectwords (et_statconfig sconfig, int val[])
This routine gets a station configuration's array of selection integers.
int et_station_config_setfunction (et_statconfig sconfig, const char *val)
This routine sets a station configuration's name of the user-defined function which is loaded from a shared library and used for selecting events.
int et_station_config_getfunction (et_statconfig sconfig, char *val)
This routine gets a station configuration's name of the user-defined function which is loaded from a shared library and used for selecting events (may be NULL).
int et_station_config_setlib (et_statconfig sconfig, const char *val)
This routine sets a station configuration's name of the shared library which is used for loading a user's function to select events.
int et_station_config_getlib (et_statconfig sconfig, char *val)
This routine gets a station configuration's name of the shared library which is used for loading a user's function to select events (may be NULL).
int et_station_config_setclass (et_statconfig sconfig, const char *val)
This routine sets a station configuration's name of the Java class which is used for loading a user's function to select events.
int et_station_config_getclass (et_statconfig sconfig, char *val)
This routine gets a station configuration's name of the Java class which is used for loading a user's function to select events.
int et_station_config_check (et_id *id, et_stat_config *sc)
This routine checks a station's configuration settings for internal inconsistencies or bad values.
int et_station_compare_parallel (et_id *id, et_stat_config *group, et_stat_config *config)
This routine compares all relevant station configuration parameters to see if both configs are compatible enough to belong in the same parallel station group.
Function Documentation
et_station_compare_parallel()
int et_station_compare_parallel (et_id * id, et_stat_config * group, et_stat_config * config)
This routine compares all relevant station configuration parameters to see if both configs are compatible enough to belong in the same parallel station group.
Parameters
id et system id.
group pointer to config of a station already in a parallel group.
config pointer to config of station to add to parallel group.
Returns
1 if compatible.
0 if NOT compatible.
References et_stat_config_t::block_mode, et_id_t::debug, ET_DEBUG_ERROR, et_logmsg(), ET_STATION_SELECT_EQUALCUE, ET_STATION_SELECT_RROBIN, et_stat_config_t::flow_mode, et_stat_config_t::prescale, and et_stat_config_t::select_mode.
et_station_config_check()
int et_station_config_check (et_id * id, et_stat_config * sc)
This routine checks a station's configuration settings for internal inconsistencies or bad values.
Parameters
id et system id.
sc station config pointer.
Returns
ET_OK if successful.
ET_ERROR if there is an internal inconsistency or bad value in the configuration.
References et_stat_config_t::block_mode, et_system_t::config, et_stat_config_t::cue, et_id_t::debug, ET_DEBUG_ERROR, ET_ERROR, et_logmsg(), ET_OK, ET_STATION_BLOCKING, ET_STATION_NONBLOCKING, ET_STATION_PARALLEL, ET_STATION_RESTORE_GC, ET_STATION_RESTORE_IN, ET_STATION_RESTORE_OUT, ET_STATION_RESTORE_REDIST, ET_STATION_SELECT_ALL, ET_STATION_SELECT_EQUALCUE, ET_STATION_SELECT_MATCH, ET_STATION_SELECT_RROBIN, ET_STATION_SELECT_USER, ET_STATION_SERIAL, et_stat_config_t::flow_mode, et_stat_config_t::fname, et_stat_config_t::lib, et_sys_config_t::nattachments, et_sys_config_t::nevents, et_stat_config_t::prescale, et_stat_config_t::restore_mode, et_stat_config_t::select_mode, et_id_t::sys, and et_stat_config_t::user_mode.
Referenced by et_station_create_at().