ET System: et_common.c File Reference
et_common.c File Reference
#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include "et_private.h"
#include "et_network.h"
Functions
void et_logmsg (char *sev, char *fmt,...)
int et_findlocality (const char *filename, et_openconfig openconfig)
This routine determines whether we are looking for the ET system locally, locally on some non-pthread-mutex-sharing operating system, or remotely.
int et_open (et_sys_id *id, const char *filename, et_openconfig openconfig)
This routine opens an ET system for client use.
int et_close (et_sys_id id)
This routine closes an open ET system.
int et_forcedclose (et_sys_id id)
This routine closes an open ET system but differs from et_close in that it automatically closes all attachments.
int et_kill (et_sys_id id)
This routine kills an open ET system.
int et_alive (et_sys_id id)
This routine tells if an open ET system is alive (heartbeat is going).
int et_wait_for_alive (et_sys_id id)
This routine waits until given ET system is alive.
char * et_perror (int error)
This routine returns a string describing the given error condition.
Function Documentation
et_findlocality()
int et_findlocality (const char * filename, et_openconfig openconfig)
This routine determines whether we are looking for the ET system locally, locally on some non-pthread-mutex-sharing operating system, or remotely.
Parameters
filename name of ET system file.
openconfig ET system open configuration.
Returns
ET_REMOTE if looking for a remote ET system.
ET_LOCAL if looking for a local ET system.
ET_LOCAL_NOSHARE if looking for a local ET system without pthread mutex sharing.
References ET_DEBUG_NONE, ET_ERROR, ET_ERROR_TIMEOUT, ET_ERROR_TOOMANY, et_findserver2(), ET_HOST_ANYWHERE, ET_HOST_AS_REMOTE, ET_HOST_LOCAL, ET_HOST_REMOTE, ET_IPADDRSTRLEN, ET_LOCAL, ET_LOCAL_NOSHARE, et_logmsg(), ET_MUTEX_SHARE, ET_REMOTE, et_sharedmutex(), et_open_config_t::host, and et_open_config_t::mode.
Referenced by et_open().
et_logmsg()
void et_logmsg (char * sev, char * fmt, ...)
Referenced by et_attach_geteventsdump(), et_attach_geteventsget(), et_attach_geteventsmake(), et_attach_geteventsput(), et_event_dump(), et_event_get(), et_event_new(), et_event_put(), et_event_setdatabuffer(), et_events_bridge(), et_events_dump(), et_events_get(), et_events_new(), et_events_new_group(), et_events_put(), et_findlocality(), et_open(), et_station_attach(), et_station_compare_parallel(), et_station_config_check(), et_station_create_at(), et_station_detach(), et_station_exists(), et_station_getattachments(), et_station_getblock(), et_station_getclass(), et_station_getcue(), et_station_getfunction(), et_station_getinputcount(), et_station_getlib(), et_station_getoutputcount(), et_station_getposition(), et_station_getprescale(), et_station_getrestore(), et_station_getselect(), et_station_getselectwords(), et_station_getstatus(), et_station_getuser(), et_station_isattached(), et_station_remove(), et_station_setblock(), et_station_setcue(), et_station_setposition(), et_station_setprescale(), et_station_setrestore(), et_station_setselectwords(), et_station_setuser(), et_system_close(), et_wakeup_all(), et_wakeup_attachment(), etr_alive(), etr_close(), etr_event_dump(), etr_event_get(), etr_event_new(), etr_event_put(), etr_events_dump(), etr_events_get(), etr_events_new(), etr_events_new_group(), etr_events_put(), etr_forcedclose(), etr_kill(), etr_open(), etr_station_attach(), etr_station_create_at(), etr_station_detach(), etr_station_exists(), etr_station_getclass(), etr_station_getfunction(), etr_station_getlib(), etr_station_getposition(), etr_station_getselectwords(), etr_station_isattached(), etr_station_remove(), etr_station_setposition(), etr_station_setselectwords(), etr_wait_for_alive(), etr_wakeup_all(), and etr_wakeup_attachment().