ET System: Attachments
Attachments
These routines are used handle attachments to stations.
Functions
int et_wakeup_attachment (et_sys_id id, et_att_id att)
This routine wakes up a specific attachment waiting to read events.
int et_wakeup_all (et_sys_id id, et_stat_id stat_id)
This routine wakes up all attachments waiting to read events.
int et_attach_geteventsput (et_sys_id id, et_att_id att_id, uint64_t *events)
This routine gets the number of events an attachment put by calling et_event_put or et_events_put.
int et_attach_geteventsget (et_sys_id id, et_att_id att_id, uint64_t *events)
This routine gets the number of events an attachment obtained by calling et_event_get, or et_events_get.
int et_attach_geteventsdump (et_sys_id id, et_att_id att_id, uint64_t *events)
This routine gets the number of events an attachment dumped by calling et_event_dump, or et_events_dump.
int et_attach_geteventsmake (et_sys_id id, et_att_id att_id, uint64_t *events)
This routine gets the number of events an attachment created by calling et_event_new, et_events_new, et_event_new_group, or et_events_new_group.
Detailed Description
These routines are used handle attachments to stations.
Function Documentation
et_attach_geteventsdump()
int et_attach_geteventsdump (et_sys_id id, et_att_id att_id, uint64_t * events)
This routine gets the number of events an attachment dumped by calling et_event_dump, or et_events_dump.
Parameters
id ET system id.
att_id attachment id.
events pointer to unsigned 64-bit int which gets filled with number of events dumped.
Returns
ET_OK if successful.
ET_ERROR if bad arg.
ET_ERROR_DEAD if ET system is dead,
ET_ERROR_CLOSED if ET system has been closed,
ET_ERROR_READ if network error reading,
ET_ERROR_WRITE if network error writing,
References et_system_t::attach, et_id_t::closed, et_system_t::config, et_id_t::debug, et_alive(), ET_DEBUG_ERROR, ET_ERROR, ET_ERROR_CLOSED, ET_ERROR_DEAD, et_logmsg(), et_mem_unlock(), et_memRead_lock(), ET_OK, ET_REMOTE, etr_attach_geteventsdump(), et_attach::events_dump, et_id_t::locality, et_sys_config_t::nattachments, and et_id_t::sys.
et_attach_geteventsget()
int et_attach_geteventsget (et_sys_id id, et_att_id att_id, uint64_t * events)
This routine gets the number of events an attachment obtained by calling et_event_get, or et_events_get.
Parameters
id ET system id.
att_id attachment id.
events pointer to unsigned 64-bit int which gets filled with number of events gotten.
Returns
ET_OK if successful.
ET_ERROR if bad arg.
ET_ERROR_DEAD if ET system is dead,
ET_ERROR_CLOSED if ET system has been closed,
ET_ERROR_READ if network error reading,
ET_ERROR_WRITE if network error writing,
References et_system_t::attach, et_id_t::closed, et_system_t::config, et_id_t::debug, et_alive(), ET_DEBUG_ERROR, ET_ERROR, ET_ERROR_CLOSED, ET_ERROR_DEAD, et_logmsg(), et_mem_unlock(), et_memRead_lock(), ET_OK, ET_REMOTE, etr_attach_geteventsget(), et_attach::events_get, et_id_t::locality, et_sys_config_t::nattachments, and et_id_t::sys.
et_attach_geteventsmake()
int et_attach_geteventsmake (et_sys_id id, et_att_id att_id, uint64_t * events)
This routine gets the number of events an attachment created by calling et_event_new, et_events_new, et_event_new_group, or et_events_new_group.
Parameters
id ET system id.
att_id attachment id.
events pointer to unsigned 64-bit int which gets filled with number of events made.
Returns
ET_OK if successful.
ET_ERROR if bad arg.
ET_ERROR_DEAD if ET system is dead,
ET_ERROR_CLOSED if ET system has been closed,
ET_ERROR_READ if network error reading,
ET_ERROR_WRITE if network error writing,
References et_system_t::attach, et_id_t::closed, et_system_t::config, et_id_t::debug, et_alive(), ET_DEBUG_ERROR, ET_ERROR, ET_ERROR_CLOSED, ET_ERROR_DEAD, et_logmsg(), et_mem_unlock(), et_memRead_lock(), ET_OK, ET_REMOTE, etr_attach_geteventsmake(), et_attach::events_make, et_id_t::locality, et_sys_config_t::nattachments, and et_id_t::sys.
et_attach_geteventsput()
int et_attach_geteventsput (et_sys_id id, et_att_id att_id, uint64_t * events)
This routine gets the number of events an attachment put by calling et_event_put or et_events_put.
Parameters
id ET system id.
att_id attachment id.
events pointer to unsigned 64-bit int which gets filled with number of events put.
Returns
ET_OK if successful.
ET_ERROR if bad arg.
ET_ERROR_DEAD if ET system is dead,
ET_ERROR_CLOSED if ET system has been closed,
ET_ERROR_READ if network error reading,
ET_ERROR_WRITE if network error writing,
References et_system_t::attach, et_id_t::closed, et_system_t::config, et_id_t::debug, et_alive(), ET_DEBUG_ERROR, ET_ERROR, ET_ERROR_CLOSED, ET_ERROR_DEAD, et_logmsg(), et_mem_unlock(), et_memRead_lock(), ET_OK, ET_REMOTE, etr_attach_geteventsput(), et_attach::events_put, et_id_t::locality, et_sys_config_t::nattachments, and et_id_t::sys.
et_wakeup_all()
int et_wakeup_all (et_sys_id id, et_stat_id stat_id)
This routine wakes up all attachments waiting to read events.
Parameters
id ET system id.
Returns
ET_OK if successful.
ET_ERROR if bad arg.
ET_ERROR_CLOSED if ET system has been closed,
ET_ERROR_WRITE if network error writing,
References et_stat_data_t::att, et_system_t::attach, et_attach::blocked, et_id_t::closed, et_system_t::config, et_list_t::cread, et_station_t::data, et_id_t::debug, err_abort, ET_ATT_BLOCKED, ET_ATT_QUIT, ET_ATT_SLEEP, ET_DEBUG_ERROR, ET_DEBUG_INFO, ET_ERROR, ET_ERROR_CLOSED, ET_LOCAL, et_logmsg(), et_mem_unlock(), et_memRead_lock(), ET_OK, etr_wakeup_all(), et_id_t::grandcentral, et_station_t::list_in, et_id_t::locality, et_sys_config_t::nattachments, et_sys_config_t::nstations, et_attach::quit, et_attach::sleep, and et_id_t::sys.
et_wakeup_attachment()
int et_wakeup_attachment (et_sys_id id, et_att_id att)
This routine wakes up a specific attachment waiting to read events.
Parameters
id ET system id.
att attachment id.
Returns
ET_OK if successful.
ET_ERROR if bad arg.
ET_ERROR_CLOSED if ET system has been closed,
ET_ERROR_WRITE if network error writing,
References et_system_t::attach, et_attach::blocked, et_id_t::closed, et_system_t::config, et_list_t::cread, et_id_t::debug, err_abort, ET_ATT_NOSLEEP, ET_ATT_QUIT, ET_ATT_UNBLOCKED, ET_DEBUG_ERROR, ET_DEBUG_INFO, ET_DEBUG_WARN, ET_ERROR, ET_ERROR_CLOSED, ET_LOCAL, et_logmsg(), et_mem_unlock(), et_memRead_lock(), ET_OK, etr_wakeup_attachment(), et_id_t::grandcentral, et_station_t::list_in, et_id_t::locality, et_sys_config_t::nattachments, et_attach::quit, et_attach::sleep, et_attach::stat, and et_id_t::sys.