#
# If evio makefiles are called locally (not in a CODA build),
# override CODA variables with EVIO variables. Necessary if
# evio is made separately from CODA.
#
# Overwrite:
#     CODA_HOME      with EVIO_HOME
#     INSTALL_DIR    with EVIO_INSTALL
#     CODA_USE64BITS with EVIO_USE64BITS
#

ifdef EVIO_HOME
  CODA_HOME = $(EVIO_HOME)
endif

ifdef EVIO_INSTALL
  INSTALL_DIR = $(EVIO_INSTALL)
endif

ifdef EVIO_USE64BITS
  CODA_USE64BITS = $(EVIO_USE64BITS)
endif
